// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef VERILATED_VSYNTH_TOP_H_
#define VERILATED_VSYNTH_TOP_H_  // guard

#include "verilated_heavy.h"

//==========

class Vsynth_top__Syms;

//----------

VL_MODULE(Vsynth_top) {
  public:

    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(i_clk,0,0);
    VL_IN8(o_clk,0,0);
    VL_IN8(reset_na,0,0);
    VL_OUT8(o_r,7,0);
    VL_OUT8(o_g,7,0);
    VL_OUT8(o_b,7,0);
    VL_OUT8(o_hs,0,0);
    VL_OUT8(o_vs,0,0);
    VL_OUT8(o_de,0,0);
    VL_OUT16(dbg_i_himax,11,0);
    VL_OUT16(dbg_o_dcpt,11,0);

    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n114_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n136_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1742_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2219_o;
        CData/*0:0*/ synth_top__DOT__p_vs;
        CData/*0:0*/ synth_top__DOT__p_de;
        CData/*7:0*/ synth_top__DOT__p_r;
        CData/*7:0*/ synth_top__DOT__p_g;
        CData/*7:0*/ synth_top__DOT__p_b;
        CData/*0:0*/ synth_top__DOT__avl_waitrequest;
        CData/*0:0*/ synth_top__DOT__app_en;
        CData/*0:0*/ synth_top__DOT__app_rd_data_valid;
        CData/*1:0*/ synth_top__DOT__src__DOT__clkdiv;
        CData/*2:0*/ synth_top__DOT__src__DOT__band;
        CData/*0:0*/ synth_top__DOT__src__DOT__in_hatch;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__o_bibu;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n186_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n252_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n374_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n397_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n424_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n452_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n925_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n960_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1037_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1081_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1083_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1258_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1282_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1298_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1336_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1345_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1405_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1832_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1923_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1926_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1956_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1979_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1990_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1994_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2014_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2129_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__scalaire_prim_v;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__scalaire_last_v;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__scalaire_bib_v;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__scalaire_off_v;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2236_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2266_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2269_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2293_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2321_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2351_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2354_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2378_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2407_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2437_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2440_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2464_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2491_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2521_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2524_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2548_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2602_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2612_o;
    };
    struct {
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2656_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2682_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2685_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2687_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2689_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2691_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2763_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2777_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2814_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2883_o;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2901_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2903_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2914_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2917_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2921_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2923_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2928_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2930_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2938_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2941_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2944_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2946_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2948_o;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2954_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3038_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3054_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3182_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3252_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3277_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3335_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3400_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3412_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3438_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3440_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3447_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3488_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3573_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3625_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3673_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3687_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3707_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3717_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4063_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4066_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4069_q;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4089_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4204_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4221_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4230_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4231_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4687_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5714_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5986_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6004_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6190_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6303_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6378_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7401_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7520_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7521_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7523_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7524_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7526_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7527_q;
    };
    struct {
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7529_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7530_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7535_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7536_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7538_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7539_q;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7542_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7543_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7561_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7565_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7589_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7590_q;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7593_o;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7594_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7597_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7598_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7601_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7602_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7605_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7606_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7608_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7609_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7612_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7613_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7615_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7616_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7619_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7620_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7623_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7624_q;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7631_o;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7632_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7635_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7636_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7639_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7640_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7643_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7644_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7646_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7647_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7648_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7650_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7652_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7653_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7654_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7656_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7657_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7659_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7660_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7662_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7663_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7664_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7667_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7668_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7671_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7672_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7675_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7676_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7679_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7680_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7682_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7683_q;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7685_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7686_q;
    };
    struct {
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7688_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7689_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7692_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7693_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7696_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7697_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7699_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7700_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7702_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7703_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7705_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7706_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7708_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7709_q;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7712_o;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7713_q;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7715_o;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7716_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7718_o;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7726_o;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7727_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7732_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7733_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7736_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7737_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7743_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7744_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7762_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7765_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7766_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7769_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7770_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7806_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7811_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7812_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7815_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7816_q;
        CData/*5:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7818_o;
        CData/*5:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7819_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7831_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7832_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7871_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7872_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7875_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7876_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7879_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7880_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7883_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7884_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7887_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7888_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7891_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7892_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7895_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7896_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7899_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7900_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7903_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7904_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7907_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7908_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7909_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7911_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7912_q;
    };
    struct {
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7914_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7915_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7917_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7918_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7920_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7921_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7923_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7924_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7926_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7927_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7929_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7930_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7932_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7933_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7934_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7935_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7937_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7938_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7940_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7941_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7943_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7944_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7946_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7947_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7950_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7951_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7954_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7955_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7957_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7958_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7964_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7965_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7966_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7967_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7968_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7988_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7990_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7991_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7993_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7994_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7996_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7997_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7999_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8000_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8002_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8003_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8005_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8006_q;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8008_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8009_q;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8011_o;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8012_q;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8014_o;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8015_q;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8017_o;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8018_q;
        CData/*5:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8020_o;
        CData/*5:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8021_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8064_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8065_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8067_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8068_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8070_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8071_q;
    };
    struct {
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8072_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8073_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8074_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8075_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8076_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8077_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8083_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8084_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8085_q;
        CData/*5:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8096_o;
        CData/*5:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8097_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8099_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8100_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8102_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8103_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8105_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8106_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8108_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8109_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8111_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8112_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8114_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8115_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8117_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8118_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8120_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8121_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8123_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8124_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8126_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8127_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8129_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8130_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8131_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8132_q;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8134_o;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8135_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8137_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8138_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8140_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8141_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8143_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8144_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8146_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8147_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8149_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8150_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8152_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8153_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8158_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8171_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8172_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8174_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8175_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8177_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8178_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8180_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8181_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8183_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8184_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8186_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8187_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8189_o;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8190_q;
    };
    struct {
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8192_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8193_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8200_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8201_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8203_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8204_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8206_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8207_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8209_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8210_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8212_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8213_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8214_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8251_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8252_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8253_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8254_q;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8255_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8316_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8320_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8321_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8323_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8324_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8326_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8327_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8328_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8329_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8330_q;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8332_o;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8333_q;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8335_o;
        CData/*4:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8336_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8338_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8339_q;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8341_o;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8342_q;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8344_o;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8345_q;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8347_o;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8348_q;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8350_o;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8351_q;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8353_o;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8354_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8356_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8357_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8359_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8360_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8362_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8363_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8365_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8366_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8368_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8369_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8371_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8372_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8374_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8375_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8377_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8378_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8380_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8381_q;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8384_o;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8385_q;
    };
    struct {
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8387_o;
        CData/*3:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8388_q;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8396_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8397_q;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8399_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8400_q;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8402_o;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8403_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8409_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8412_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8413_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8415_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8416_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8452_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8453_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8463_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8464_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8466_o;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8467_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8475_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8476_q;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8478_o;
        CData/*1:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8479_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8482_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8484_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8518_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8519_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8547_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8548_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8555_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8556_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8557_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8558_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8564_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8566_q;
        CData/*7:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8568_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8570_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8572_q;
        CData/*0:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8574_q;
        CData/*2:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n14071_o;
        CData/*1:0*/ synth_top__DOT__bridge__DOT__state;
        CData/*7:0*/ synth_top__DOT__bridge__DOT__beat;
        CData/*7:0*/ synth_top__DOT__bridge__DOT__blen_q;
        CData/*0:0*/ synth_top__DOT__bridge__DOT__wr_go;
        CData/*0:0*/ synth_top__DOT__bridge__DOT__rd_go;
        CData/*3:0*/ synth_top__DOT__ddr__DOT__cnt;
        CData/*0:0*/ synth_top__DOT__ddr__DOT__rdy;
        SData/*9:0*/ synth_top__DOT__src__DOT__hcnt;
        SData/*9:0*/ synth_top__DOT__src__DOT__vcnt;
        SData/*9:0*/ synth_top__DOT__src__DOT__frame;
        SData/*8:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n646_o;
        SData/*8:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n831_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1658_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1660_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4647_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4649_o;
        SData/*15:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4716_o;
        SData/*8:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4741_o;
        SData/*9:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5461_o;
        SData/*9:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5481_o;
        SData/*9:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5499_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6019_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6020_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6021_o;
    };
    struct {
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6022_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6023_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6172_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6174_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6176_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6178_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6192_o;
        SData/*15:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6405_o;
        SData/*8:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6429_o;
        SData/*9:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7142_o;
        SData/*9:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7162_o;
        SData/*9:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7180_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7546_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7547_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7550_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7551_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7554_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7555_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7558_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7559_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7562_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7563_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7566_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7567_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7570_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7571_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7574_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7575_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7578_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7579_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7582_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7583_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7586_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7587_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7774_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7775_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7778_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7779_q;
        SData/*12:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7781_o;
        SData/*12:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7782_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7792_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7793_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7796_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7797_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7799_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7800_q;
        SData/*12:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7803_o;
        SData/*12:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7804_q;
        SData/*12:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7807_o;
        SData/*12:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7808_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8029_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8030_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8032_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8033_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8035_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8036_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8038_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8039_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8041_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8042_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8044_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8045_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8047_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8049_o;
    };
    struct {
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8050_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8052_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8053_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8055_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8056_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8058_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8059_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8061_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8062_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8078_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8079_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8081_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8082_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8087_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8088_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8090_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8091_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8093_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8094_q;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8154_q;
        SData/*14:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8159_o;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8168_o;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8169_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8233_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8235_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8237_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8239_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8241_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8257_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8259_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8261_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8263_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8265_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8266_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8268_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8269_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8271_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8272_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8274_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8275_q;
        SData/*14:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8277_o;
        SData/*14:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8278_q;
        SData/*14:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8280_o;
        SData/*14:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8281_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8283_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8284_q;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8289_o;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8290_q;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8292_o;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8293_q;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8295_o;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8296_q;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8298_o;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8299_q;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8301_o;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8302_q;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8304_o;
        SData/*13:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8305_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8307_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8309_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8311_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8313_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8405_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8406_q;
    };
    struct {
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8417_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8418_q;
        SData/*12:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8457_o;
        SData/*12:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8458_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8469_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8470_q;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8472_o;
        SData/*11:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8473_q;
        SData/*15:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8497_q;
        SData/*15:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8499_q;
        SData/*9:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8549_q;
        SData/*9:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8550_q;
        VlWide<4>/*127:0*/ synth_top__DOT__app_rd_data;
        IData/*23:0*/ synth_top__DOT__src__DOT__bar_rgb;
        IData/*23:0*/ synth_top__DOT__src__DOT__pat;
        VlWide<4>/*119:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__i_shift;
        IData/*16:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n492_o;
        IData/*16:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n511_o;
        IData/*16:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n530_o;
        VlWide<3>/*95:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n574_o;
        VlWide<3>/*95:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n632_o;
        VlWide<4>/*127:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1038_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n1326_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n2735_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3212_o;
        VlWide<5>/*143:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3574_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3626_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n3648_o;
        VlWide<3>/*71:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4315_o;
        VlWide<3>/*71:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4369_o;
        IData/*20:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4500_o;
        IData/*20:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4519_o;
        IData/*20:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4540_o;
        IData/*20:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4559_o;
        IData/*20:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4580_o;
        IData/*20:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4599_o;
        IData/*20:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4620_o;
        VlWide<5>/*146:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5284_o;
        VlWide<3>/*95:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5380_o;
        VlWide<6>/*161:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5633_o;
        IData/*18:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5643_o;
        IData/*18:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5662_o;
        IData/*18:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5680_o;
        VlWide<4>/*107:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5723_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5726_o;
        VlWide<21>/*671:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5730_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6246_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6253_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6286_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6288_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6290_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6292_o;
        VlWide<3>/*95:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6304_o;
        VlWide<3>/*95:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6363_o;
        VlWide<5>/*146:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6967_o;
        VlWide<3>/*95:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7063_o;
        VlWide<6>/*161:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7311_o;
        IData/*18:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7321_o;
        IData/*18:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7340_o;
        IData/*18:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7358_o;
        VlWide<5>/*143:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7432_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7532_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7533_q;
        VlWide<4>/*119:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7720_q;
    };
    struct {
        VlWide<4>/*127:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7722_o;
        VlWide<4>/*127:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7723_q;
        VlWide<4>/*127:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7746_o;
        VlWide<4>/*127:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7747_q;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7749_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7750_q;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7752_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7753_q;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7756_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7757_q;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7760_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7761_q;
        IData/*24:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7784_o;
        IData/*24:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7785_q;
        IData/*16:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7788_o;
        IData/*16:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7789_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7839_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7840_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7843_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7844_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7847_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7848_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7851_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7852_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7855_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7856_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7859_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7860_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7863_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7864_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7867_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7868_q;
        VlWide<4>/*127:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7960_o;
        VlWide<4>/*127:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7961_q;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7970_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7971_q;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7974_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7975_q;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7977_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7978_q;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7980_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7981_q;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7983_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7984_q;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7986_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7987_q;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8162_o;
        IData/*31:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8163_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8165_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8166_q;
        VlWide<5>/*143:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8197_o;
        VlWide<5>/*143:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8198_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8246_q;
        VlWide<4>/*107:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8285_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8410_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8421_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8422_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8425_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8426_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8429_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8430_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8433_o;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8434_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8437_o;
    };
    struct {
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8438_q;
        VlWide<21>/*671:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8439_q;
        VlWide<3>/*95:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8441_q;
        VlWide<3>/*95:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8443_q;
        VlWide<3>/*71:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8445_q;
        VlWide<5>/*143:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8448_q;
        IData/*24:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8460_o;
        IData/*24:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8461_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8485_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8487_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8500_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8502_q;
        VlWide<5>/*146:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8503_q;
        VlWide<5>/*146:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8506_q;
        VlWide<3>/*95:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8509_q;
        VlWide<3>/*95:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8511_q;
        VlWide<320>/*10239:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8515_q;
        VlWide<320>/*10239:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8516_q;
        VlWide<320>/*10239:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8517_q;
        VlWide<3>/*71:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8536_q;
        VlWide<3>/*71:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8538_q;
        VlWide<3>/*71:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8539_q;
        VlWide<3>/*71:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8540_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8542_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8543_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8544_q;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8546_q;
        VlWide<6>/*161:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8551_q;
        VlWide<6>/*161:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8554_q;
        IData/*24:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8590_o;
        IData/*24:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8591_q;
        VlWide<4>/*127:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8593_data;
        VlWide<4>/*127:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8596_data;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8599_data;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8602_data;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8605_data;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8608_data;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8611_data;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8614_data;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8617_data;
        IData/*23:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8620_data;
        IData/*24:0*/ synth_top__DOT__bridge__DOT__addr_q;
        QData/*50:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n689_o;
        QData/*50:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n875_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4252_o;
        QData/*40:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4907_o;
        QData/*40:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n4980_o;
        QData/*40:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5053_o;
        QData/*40:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5136_o;
        QData/*40:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5209_o;
        QData/*40:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5282_o;
        QData/*59:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5450_o;
        QData/*35:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n5734_o;
        QData/*40:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6593_o;
        QData/*40:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6666_o;
        QData/*40:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6739_o;
        QData/*40:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6819_o;
        QData/*40:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6892_o;
        QData/*40:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n6965_o;
        QData/*59:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n7132_o;
        QData/*62:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8454_q;
        QData/*35:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8455_q;
        QData/*50:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8488_q;
        QData/*50:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8490_q;
    };
    struct {
        QData/*50:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8495_o;
        QData/*50:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8496_q;
        QData/*59:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8512_q;
        QData/*59:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8514_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8520_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8521_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8522_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8523_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8524_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8525_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8526_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8527_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8528_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8529_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8530_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8531_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8533_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n8534_q;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9014_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9016_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9018_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9020_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9022_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9024_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9026_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9028_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9030_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9032_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9034_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9036_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9038_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9040_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9042_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9044_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9054_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9440_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9442_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9444_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9446_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9448_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9450_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9452_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9454_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9456_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9458_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9460_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9462_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9464_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9466_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9468_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9470_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9480_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9866_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9868_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9870_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9872_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9874_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9876_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9878_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9880_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9882_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9884_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9886_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9888_o;
    };
    struct {
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9890_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9892_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9894_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9896_o;
        QData/*39:0*/ synth_top__DOT__dut__DOT__u_ascal__DOT__n9906_o;
        VlUnpacked<VlWide<4>/*127:0*/, 256> synth_top__DOT__dut__DOT__u_ascal__DOT__i_dpram;
        VlUnpacked<VlWide<4>/*127:0*/, 256> synth_top__DOT__dut__DOT__u_ascal__DOT__o_dpram;
        VlUnpacked<IData/*23:0*/, 2048> synth_top__DOT__dut__DOT__u_ascal__DOT__o_line0;
        VlUnpacked<IData/*23:0*/, 2048> synth_top__DOT__dut__DOT__u_ascal__DOT__o_line1;
        VlUnpacked<IData/*23:0*/, 2048> synth_top__DOT__dut__DOT__u_ascal__DOT__o_line2;
        VlUnpacked<IData/*23:0*/, 2048> synth_top__DOT__dut__DOT__u_ascal__DOT__o_line3;
        VlUnpacked<IData/*23:0*/, 256> synth_top__DOT__dut__DOT__u_ascal__DOT__o_linf0;
        VlUnpacked<IData/*23:0*/, 256> synth_top__DOT__dut__DOT__u_ascal__DOT__o_linf1;
        VlUnpacked<IData/*23:0*/, 256> synth_top__DOT__dut__DOT__u_ascal__DOT__o_linf2;
        VlUnpacked<IData/*23:0*/, 256> synth_top__DOT__dut__DOT__u_ascal__DOT__o_linf3;
        VlUnpacked<VlWide<4>/*127:0*/, 262144> synth_top__DOT__ddr__DOT__ram;
        VlUnpacked<IData/*18:0*/, 13> synth_top__DOT__ddr__DOT__pipe;
    };

    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    CData/*2:0*/ __Vtableidx1;
    CData/*5:0*/ __Vtableidx2;
    CData/*5:0*/ __Vtableidx3;
    CData/*4:0*/ __Vtableidx4;
    CData/*5:0*/ __Vtableidx5;
    CData/*7:0*/ __Vtableidx6;
    CData/*5:0*/ __Vtableidx7;
    CData/*7:0*/ __Vtableidx8;
    CData/*5:0*/ __Vtableidx9;
    CData/*5:0*/ __Vtableidx10;
    CData/*5:0*/ __Vtableidx11;
    CData/*7:0*/ __Vtableidx12;
    CData/*0:0*/ __VinpClk__TOP__synth_top__DOT__dut__DOT__u_ascal__DOT__n114_o;
    CData/*0:0*/ __VinpClk__TOP__synth_top__DOT__dut__DOT__u_ascal__DOT__n136_o;
    CData/*0:0*/ __VinpClk__TOP__synth_top__DOT__dut__DOT__u_ascal__DOT__n1742_o;
    CData/*0:0*/ __VinpClk__TOP__synth_top__DOT__dut__DOT__u_ascal__DOT__n2219_o;
    CData/*0:0*/ __Vclklast__TOP__o_clk;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__synth_top__DOT__dut__DOT__u_ascal__DOT__n114_o;
    CData/*0:0*/ __Vclklast__TOP__i_clk;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__synth_top__DOT__dut__DOT__u_ascal__DOT__n136_o;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__synth_top__DOT__dut__DOT__u_ascal__DOT__n1742_o;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__synth_top__DOT__dut__DOT__u_ascal__DOT__n2219_o;
    CData/*0:0*/ __Vchglast__TOP__synth_top__DOT__dut__DOT__u_ascal__DOT__n114_o;
    CData/*0:0*/ __Vchglast__TOP__synth_top__DOT__dut__DOT__u_ascal__DOT__n136_o;
    CData/*0:0*/ __Vchglast__TOP__synth_top__DOT__dut__DOT__u_ascal__DOT__n1742_o;
    CData/*0:0*/ __Vchglast__TOP__synth_top__DOT__dut__DOT__u_ascal__DOT__n2219_o;
    IData/*18:0*/ synth_top__DOT__ddr__DOT____Vlvbound2;
    static VlUnpacked<IData/*23:0*/, 8> __Vtable1_synth_top__DOT__src__DOT__bar_rgb;
    static VlUnpacked<CData/*0:0*/, 64> __Vtable2_synth_top__DOT__dut__DOT__u_ascal__DOT__n2914_o;
    static VlUnpacked<CData/*0:0*/, 64> __Vtable3_synth_top__DOT__dut__DOT__u_ascal__DOT__n2917_o;
    static VlUnpacked<CData/*0:0*/, 32> __Vtable4_synth_top__DOT__dut__DOT__u_ascal__DOT__n2921_o;
    static VlUnpacked<CData/*0:0*/, 64> __Vtable5_synth_top__DOT__dut__DOT__u_ascal__DOT__n2923_o;
    static VlUnpacked<CData/*1:0*/, 256> __Vtable6_synth_top__DOT__dut__DOT__u_ascal__DOT__n2928_o;
    static VlUnpacked<CData/*0:0*/, 64> __Vtable7_synth_top__DOT__dut__DOT__u_ascal__DOT__n2930_o;
    static VlUnpacked<CData/*1:0*/, 256> __Vtable8_synth_top__DOT__dut__DOT__u_ascal__DOT__n2938_o;
    static VlUnpacked<CData/*0:0*/, 64> __Vtable9_synth_top__DOT__dut__DOT__u_ascal__DOT__n2944_o;
    static VlUnpacked<CData/*0:0*/, 64> __Vtable10_synth_top__DOT__dut__DOT__u_ascal__DOT__n2946_o;
    static VlUnpacked<CData/*0:0*/, 64> __Vtable11_synth_top__DOT__dut__DOT__u_ascal__DOT__n2948_o;
    static VlUnpacked<CData/*3:0*/, 256> __Vtable12_synth_top__DOT__dut__DOT__u_ascal__DOT__n2954_o;

    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    Vsynth_top__Syms* __VlSymsp;  // Symbol table

    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vsynth_top);  ///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// If contextp is null, then the model will use the default global context
    /// If name is "", then makes a wrapper with a
    /// single model invisible with respect to DPI scope names.
    Vsynth_top(VerilatedContext* contextp, const char* name = "TOP");
    Vsynth_top(const char* name = "TOP")
      : Vsynth_top(nullptr, name) {}
    /// Destroy the model; called (often implicitly) by application code
    ~Vsynth_top();

    // API METHODS
    /// Return current simulation context for this model.
    /// Used to get to e.g. simulation time via contextp()->time()
    VerilatedContext* contextp();
    /// Evaluate the model.  Application must call when inputs change.
    void eval() { eval_step(); }
    /// Evaluate when calling multiple units/models per time step.
    void eval_step();
    /// Evaluate at end of a timestep for tracing, when using eval_step().
    /// Application must call after all eval() and before time changes.
    void eval_end_step() {}
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();

    // INTERNAL METHODS
    static void _eval_initial_loop(Vsynth_top__Syms* __restrict vlSymsp);
    void __Vconfigure(Vsynth_top__Syms* symsp, bool first);
  private:
    static QData _change_request(Vsynth_top__Syms* __restrict vlSymsp);
    static QData _change_request_1(Vsynth_top__Syms* __restrict vlSymsp);
  public:
    static void _combo__TOP__12(Vsynth_top__Syms* __restrict vlSymsp);
  private:
    static void _ctor_var_reset(Vsynth_top* self) VL_ATTR_COLD;
  public:
    static void _eval(Vsynth_top__Syms* __restrict vlSymsp);
  private:
#ifdef VL_DEBUG
    void _eval_debug_assertions();
#endif  // VL_DEBUG
  public:
    static void _eval_initial(Vsynth_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _eval_settle(Vsynth_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__1(Vsynth_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _sequent__TOP__13(Vsynth_top__Syms* __restrict vlSymsp);
    static void _sequent__TOP__14(Vsynth_top__Syms* __restrict vlSymsp);
    static void _sequent__TOP__2(Vsynth_top__Syms* __restrict vlSymsp);
    static void _sequent__TOP__3(Vsynth_top__Syms* __restrict vlSymsp);
    static void _sequent__TOP__4(Vsynth_top__Syms* __restrict vlSymsp);
    static void _sequent__TOP__5(Vsynth_top__Syms* __restrict vlSymsp);
    static void _sequent__TOP__6(Vsynth_top__Syms* __restrict vlSymsp);
    static void _sequent__TOP__7(Vsynth_top__Syms* __restrict vlSymsp);
    static void _sequent__TOP__8(Vsynth_top__Syms* __restrict vlSymsp);
    static void _sequent__TOP__9(Vsynth_top__Syms* __restrict vlSymsp);
    static void _settle__TOP__10(Vsynth_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__11(Vsynth_top__Syms* __restrict vlSymsp) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
