// game_config.vh is generated by `python3 tools/merge_roms.py <game>` and
// must match the ROM hex files: for MCR-1 it defines GAME_KICK / GAME_SOLARFOX.
`include "game_config.vh"

// Tang Console 60K Top-Level Wrapper for the MCR-1 Arcade Core (Kick,
// Kickman, Solar Fox). This is the MCR-2 top (mcr2_console60k_top.sv) with
// the core swapped for src/rtl/mcr1.vhd; ALL shared infrastructure (PLL,
// DDR3 framebuffer/HDMI, analog video, USB, SD loader + prefs, OSD, beacon,
// audio) is identical and any fix there should be mirrored back to the MCR-2
// top. MCR-1 differences, all local to this file: 15-bit CPU ROM + MCR-1
// download map, 4-bit core RGB truncated to the shared 3:3:3 pipeline, the
// per-game input mux, and the core's flip/pause inputs.
module mcr1_console60k_top (
    input        sys_clk,       // 50 MHz on-board oscillator (pin V22)
    input        s1,            // User key AA13 - ACTIVE LOW on console (pull-up)
    input        reset2,        // User key AB13 - ACTIVE LOW on console (pull-up)

    // DVI/HDMI output.
    // hpd_en drives the dock's HDMI enable. Sipeed's own NEO_DOCK example
    // drives this pin at DRIVE=12; nand2mario's cores leave it unassigned
    // (tri-stated with a weak internal pull-up), which is what we did too.
    // If the net has an external pull-down, that weak pull-up loses and the
    // dock's HDMI stays disabled - and because JTAG reconfiguration does not
    // power-cycle the board, whether a previous core left the line high can
    // decide if a picture appears. Drive it explicitly.
    output       hpd_en,
    output       tmds_clk_p,
    output       tmds_clk_n,
    output [2:0] tmds_d_p,
    output [2:0] tmds_d_n,

    // On-SOM DDR3 (framebuffer backing store; pins from gbatang console60k)
    output [14:0] ddr_addr,
    output [2:0]  ddr_bank,
    output        ddr_cs,
    output        ddr_ras,
    output        ddr_cas,
    output        ddr_we,
    output        ddr_ck,
    output        ddr_ck_n,
    output        ddr_cke,
    output        ddr_odt,
    output        ddr_reset_n,
    output [1:0]  ddr_dm,
    inout  [15:0] ddr_dq,
    inout  [1:0]  ddr_dqs,
    inout  [1:0]  ddr_dqs_n,

    // PMOD sockets, repurposed to host the Digilent PmodVGA directly.
    // (Desk buttons retired - inputs come from the USB pad and board keys.)
    // Sipeed socket IO order differs from Digilent pin order; the physical
    // row/socket orientation is resolved at runtime by the two map_* straps.
    output [7:0] pmod0_io,
    output [7:0] pmod1_io,
    input        map_rows_n,     // J10-39 strap: open/GND = try both
    input        map_sock_n,     // J10-40 strap: open/GND = try both

    // Digilent PmodVGA (4:4:4 + HS/VS) wired to J10 header - see CST for the
    // jumper recipe. Analog output has no line buffer -> no shimmer/tearing.
    output [3:0] vga_r,
    output [3:0] vga_g,
    output [3:0] vga_b,
    output       vga_hs,
    output       vga_vs,

    // 15/31 kHz select strap on J10 (internal pull-up):
    // open = 31 kHz progressive (VGA monitor), jumper to GND = 15 kHz
    // native arcade timing (CRT / OSSC / RetroTink; VGA LCDs will not sync)
    input        mode15_n,

    // USB-A port 1 (left) - USB HID host (15k pulldowns are on the board)
    inout        usb1_dp,
    inout        usb1_dn,

    // MicroSD card (SPI mode) - optional ROM source, see rom_loader.sv
    output       sd_clk,
    output       sd_cmd,      // MOSI
    input        sd_dat0,     // MISO
    output       sd_dat3,     // CS

    // DDR3/HDMI bring-up debug (J10 pins 21-24; see comment at the logic)
    output [3:0] debug_o,

    // Status beacon on the FPGA->BL616 UART (shows up as USB-C serial,
    // 115200 8N1): one "FB c_ r_ x____ q__" line every ~0.5s
    output       uart_tx,

    // PWM Audio output
    output       audio_l,
    output       audio_r
);

assign hpd_en = 1'b1;   // enable the dock's HDMI path

// --- Clock Generation ---
wire clk_sys;  // 40 MHz  (Core system clock, generates 20 MHz pixel enable)
wire clk_p5;   // 125 MHz (HDMI 5x pixel clock)
wire pll_locked;

wire clk50_pll;  // PLL-buffered 50 MHz for the DDR3 controller/mDRP (clk_g).
                 // Feeding the raw pad clock there put a derived clock on
                 // generic routing (PR1014) and the DDR3 IP never came up.
gowin_pll_mcr2 pll_inst (
    .clkin(sys_clk),
    .clk_sys(clk_sys),
    .clk_p5(clk_p5),
    .clk_50(clk50_pll),
    .lock(pll_locked)
);

// 27 MHz reference for the DDR3 framebuffer's internal PLLs (720p + DDR3)
wire clk27;
pll_27 pll27_inst (
    .clkin(sys_clk),
    .clkout0(clk27)
);

// Second PLLA: 50 MHz -> exactly 12 MHz for the USB HID host
// (VCO = 50*18 = 900 MHz, ODIV0 = 75; config from nand2mario's usb_hid_host)
wire clk_usb;
gowin_pll_usb pll_usb_inst (
    .clkin(sys_clk),
    .clkout(clk_usb)
);

// --- Reset Generation ---
// Unlike the Primer 25K (buttons active high w/ pulldown), the Tang Console's
// user keys are active LOW with pull-ups. Invert once here; the rest of the
// design keys off the active-high key_s1/key_s2 exactly like the 25K top.
wire key_s1 = ~s1;
wire key_s2 = ~reset2;

// 15 kHz strap, synchronized into the core clock domain (active low pin).
// Live toggling works; if the picture is disturbed after moving the jumper,
// press S1 (reset) once.
reg mode15_s1 = 0, mode15_s2 = 0;
always @(posedge clk_sys) begin
    mode15_s1 <= ~mode15_n;
    mode15_s2 <= mode15_s1;
end
wire tv15khz = mode15_s2;

// (Video note: the DDR3 framebuffer captures whatever timing the core emits,
// so HDMI stays alive in 15 kHz mode too - capture height drops to 240
// lines per field and the upscaler adapts.)

reg [7:0] reset_cnt = 255;
wire      rom_ready;                          // ROM image settled
wire core_reset_raw = (reset_cnt != 0);       // resets the SD loader itself

// core_reset is REGISTERED: it fans out to every synchronous reset in the
// core, and as a combinational function of reset_cnt it became the critical
// path (deterministic -0.35ns on the shollow build). One extra cycle of
// reset latency costs nothing.
reg core_reset = 1'b1;
wire       osd_nocard;   // INSERT CARD screen owns the display
// INSERT CARD screen (no baked ROMs any more, so a missing card has nothing
// to fall back on). Two things have to be true while it is up:
//  1. The core must NOT be held in reset. mcr3/mcr2/mcr1.vhd hold hcnt/vcnt
//     at zero under reset, so resetting stops the raster - and the OSD draws
//     in the core raster domain, so the message would vanish into a black
//     screen. The core free-runs on blank RAM instead; osd_nocard blanks its
//     video so none of that garbage is visible behind the text.
//  2. When a card finally loads, the core has been running for a while on
//     nonsense and must be restarted, or the Z80 carries on from wherever it
//     wandered to. Pulse reset on the way out of the screen.
reg       nocard_d      = 1'b0;
reg [7:0] nocard_exit_r = 8'd0;   // ~6us reset pulse on card-found
always @(posedge clk_sys) begin
    nocard_d <= osd_nocard;
    if (nocard_d && !osd_nocard)      nocard_exit_r <= 8'hFF;
    else if (nocard_exit_r != 8'd0)   nocard_exit_r <= nocard_exit_r - 8'd1;
end
always @(posedge clk_sys)
    core_reset <= core_reset_raw
               || (!rom_ready && !osd_nocard)
               || (nocard_exit_r != 8'd0);

// Game selection. game_id picks the input/DIP mapping at RUNTIME; game_slot
// tells the SD loader which pack slot to (re)load. Both owned by the OSD
// menu (Select+Start). The power-on default is whatever merge_roms.py baked
// into BSRAM, so map and ROMs always match at boot. MCR-1 roster (pack slot
// order): 0 = Kick, 1 = Solar Fox. Kickman shares Kick's input map.
`ifdef GAME_SOLARFOX
localparam [2:0] GAME_DEFAULT = 3'd1;
`else
localparam [2:0] GAME_DEFAULT = 3'd0;   // Kick / Kickman
`endif

wire [2:0] game_id;      // game the core is running (from the OSD)
wire [3:0] game_slot;    // SD pack slot the loader (re)loads
wire       osd_restart;  // OSD pulse: restart the loader with game_slot
wire       osd_active;   // menu open -> game inputs masked below

always @(posedge clk_sys) begin
    if (key_s1 || !pll_locked) begin
        reset_cnt <= 255;
    end else if (reset_cnt != 0) begin
        reset_cnt <= reset_cnt - 8'd1;
    end
end

// --- ROM source ---------------------------------------------------------
// The INIT_FILE contents are the power-on default (whatever game
// `merge_roms.py` last generated - Tron by default), so the board always
// boots something even with no SD card. When a card holding a valid pack is
// present, rom_loader overwrites these memories before the core leaves
// reset and the DIP-selected game runs instead.
wire        sd_ready, sd_err, sd_rd_start, sd_rd_done, sd_dv;
wire [7:0]  sd_dout;
wire [31:0] sd_sector;
wire        sd_wr_start, sd_wr_next, sd_wr_done;
wire [7:0]  sd_wr_din;
wire [17:0] dl_addr;   // widened for pack v2 (loader port)
wire [7:0]  dl_data;
wire        dl_wr;
wire        ldr_done, ldr_error, ldr_saved;
wire [3:0]  ldr_slot;      // slot actually loaded (SD-saved pref at boot)
wire        osd_save;      // OSD: persist the selection to the prefs sector

// Core runs once the loader has finished, or as soon as it gives up on a
// missing/unreadable card (then the baked-in ROMs stand).
assign rom_ready = ldr_done | ldr_error;

sd_reader #(.CLK_HZ(40_000_000)) sd (
    .clk(clk_sys), .rst(core_reset_raw),
    .ready(sd_ready), .err(sd_err),
    .rd_start(sd_rd_start), .rd_sector(sd_sector),
    .dout(sd_dout), .dout_valid(sd_dv), .rd_done(sd_rd_done),
    .wr_start(sd_wr_start), .wr_din(sd_wr_din),
    .wr_next(sd_wr_next), .wr_done(sd_wr_done), .wr_err(),
    .sclk(sd_clk), .mosi(sd_cmd), .miso(sd_dat0), .cs_n(sd_dat3)
);

rom_loader #(.PACK_BASE(32'd2048), .SLOT_SECTORS(256), .FAMILY(8'd0)) loader (
    .clk(clk_sys), .rst(core_reset_raw | osd_restart),
    .slot(game_slot),
    // Boot consults the SD-saved preference; an OSD-commanded reload
    // (menu open) loads exactly the slot the user picked.
    // INSERT CARD retries still honour the saved game (osd_active alone
    // would force prefs off and lose the owner's selection)
    .use_prefs(~osd_active | osd_nocard),
    .save_req(osd_save), .saved(ldr_saved),
    .cur_slot(ldr_slot),
    .sd_ready(sd_ready), .sd_err(sd_err),
    .sd_rd_start(sd_rd_start), .sd_sector(sd_sector),
    .sd_dout(sd_dout), .sd_dout_valid(sd_dv), .sd_rd_done(sd_rd_done),
    .sd_wr_start(sd_wr_start), .sd_wr_din(sd_wr_din),
    .sd_wr_next(sd_wr_next), .sd_wr_done(sd_wr_done),
    .dl_addr(dl_addr), .dl_data(dl_data), .dl_wr(dl_wr),
    .v2_mode(), .done(ldr_done), .error(ldr_error)
);

// Download decode for the two ROMs that live here (the gfx ROMs decode
// inside mcr1.vhd at 0x10000/0x18000/0x19000). MCR-1 map (differs from
// MCR-2): CPU 0x00000-0x07FFF (bit16=0,bit15=0), sound 0x08000-0x0BFFF
// (bit16=0,bit15=1,bit14=0). Matches tools/merge_roms.py's MCR-1 layout.
wire cpu_rom_we = dl_wr && !dl_addr[16] && !dl_addr[15];
wire snd_rom_we = dl_wr && !dl_addr[16] &&  dl_addr[15] && !dl_addr[14];

wire [14:0] rom_addr;   // MCR-1 CPU addr is 15-bit (0x0000-0x6FFF)
wire [7:0]  rom_do;
wire [13:0] snd_addr;
wire [7:0]  snd_do;

dpram #(
    .dWidth(8),
    .aWidth(15),
    // NO BAKE (licensing): starts blank, SD pack is the only source.
    // LOADABLE keeps port B writable (empty INIT_FILE alone = read-only B).
    .LOADABLE(1)
) rom_cpu_inst (
    .clk_a(clk_sys),
    .we_a(1'b0),
    .addr_a(rom_addr),
    .d_a(8'h00),
    .q_a(rom_do),

    .clk_b(clk_sys),
    .we_b(cpu_rom_we),
    .addr_b(dl_addr[14:0]),
    .d_b(dl_data),
    .q_b() // port B is the ROM download port
);

dpram #(
    .dWidth(8),
    .aWidth(14),
    .LOADABLE(1)          // NO BAKE (licensing) - see the CPU ROM above
) rom_snd_inst (
    .clk_a(clk_sys),
    .we_a(1'b0),
    .addr_a(snd_addr),
    .d_a(8'h00),
    .q_a(snd_do),

    .clk_b(clk_sys),
    .we_b(snd_rom_we),
    .addr_b(dl_addr[13:0]),
    .d_b(dl_data),
    .q_b() // port B is the ROM download port
);

// --- USB HID host (gamepad on USB-A port 1) -----------------------------------
// nand2mario usb_hid_host: low-speed USB, standard HID pads (DInput). The
// board provides the 15k host pulldowns and 5V VBUS. Runs at 12 MHz.
//
// Reset policy - learned from the flash-boot regression: a JTAG load starts
// the design on a board that has been powered for minutes (pad enumerated,
// idle), but an SPI-flash boot starts it right after configuration, while
// the pad's own MCU is still booting. The original 21 us reset ran
// enumeration once into a not-yet-ready pad; the engine then sticks in a
// state it cannot leave on its own - CONFIRMED on hardware: even
// unplug/replug does not revive it, only reset does. So recovery must come
// from out here, and it must not rely on the engine's conerr flag alone
// (the stuck state may never raise it):
//   - hold the host in reset ~350 ms at power-on (slow pads);
//   - whenever NO device is enumerated (typ == 0) or conerr is up,
//     continuously for ~2.8 s, pulse reset and re-enumerate.
// With no pad plugged this is a harmless slow retry loop; late-booting and
// hot-plugged pads get picked up on the next cycle.
reg [22:0] usb_rst_cnt = 23'd0;
reg [24:0] usb_idle_cnt = 25'd0;
wire usb_resetn = usb_rst_cnt[22];        // 2^22 / 12 MHz = 350 ms
wire usb_conerr;
wire [1:0] usb_typ;
always @(posedge clk_usb) begin
    if (!usb_resetn)
        usb_rst_cnt <= usb_rst_cnt + 23'd1;
    if (!usb_resetn || (usb_typ != 2'd0 && !usb_conerr))
        usb_idle_cnt <= 25'd0;
    else begin
        usb_idle_cnt <= usb_idle_cnt + 25'd1;
        if (&usb_idle_cnt) usb_rst_cnt <= 23'd0;  // ~2.8 s dead: re-init
    end
end

wire pad_l, pad_r, pad_u, pad_d;
wire pad_a, pad_b, pad_x, pad_y, pad_sel, pad_sta;

usb_hid_host usb1 (
    .usbclk(clk_usb),
    .usbrst_n(usb_resetn),
    .usb_dm(usb1_dn),
    .usb_dp(usb1_dp),
    .typ(usb_typ),
    .report(),
    .conerr(usb_conerr),
    .key_modifiers(), .key1(), .key2(), .key3(), .key4(),
    .mouse_btn(), .mouse_dx(), .mouse_dy(),
    .game_l(pad_l), .game_r(pad_r), .game_u(pad_u), .game_d(pad_d),
    .game_a(pad_a), .game_b(pad_b), .game_x(pad_x), .game_y(pad_y),
    .game_sel(pad_sel), .game_sta(pad_sta),
    .dbg_hid_report()
);

// Synchronize the (active-high, 12 MHz-domain) pad bits into clk_sys
reg [9:0] pad_sync1 = 0, pad_sync2 = 0;
reg [1:0] usb_typ_s1 = 0, usb_typ_s2 = 0;   // quasi-static, for the beacon
always @(posedge clk_sys) begin
    pad_sync1 <= {pad_l, pad_r, pad_u, pad_d, pad_a, pad_b, pad_x, pad_y, pad_sel, pad_sta};
    pad_sync2 <= pad_sync1;
    usb_typ_s1 <= usb_typ;
    usb_typ_s2 <= usb_typ_s1;
end
wire u_left  = pad_sync2[9], u_right = pad_sync2[8];
wire u_up    = pad_sync2[7], u_down  = pad_sync2[6];
wire u_btn_a = pad_sync2[5], u_btn_b = pad_sync2[4];
wire u_btn_x = pad_sync2[3], u_btn_y = pad_sync2[2];
wire u_sel   = pad_sync2[1], u_sta   = pad_sync2[0];

// Core video signals, declared ahead of everything that references them.
// The MCR-1 core emits 4-bit RGB; the shared framebuffer/OSD/analog pipeline
// is 3:3:3, so take the top 3 bits (one LSB of colour depth dropped, which
// is imperceptible). core_r/g/b come from the core instance below.
wire [3:0] core_r, core_g, core_b;
wire [2:0] r = core_r[3:1];
wire [2:0] g = core_g[3:1];
wire [2:0] b = core_b[3:1];
wire       hblank, vblank;
wire       hs, vs, cs;

// --- Core Controls & Switch Mapping (runtime mux, verified vs MAME mcr.cpp) --
// game_id selects the map (OSD menu); game_config.vh only decides which
// game's ROMs are BAKED into BSRAM (no-card boot). Common pad decode: dpad =
// joystick, Start = Start1, Select = Coin1 (board key 2 also pulses Coin 1).
// Inputs masked while the OSD is open; d-pad masked while Select held
// (Select+dpad = capture-delay tuning).
localparam [2:0] GID_KICK     = 3'd0,
                 GID_SOLARFOX = 3'd1;

wire m_left    = u_left  & ~u_sel & ~osd_active;
wire m_right   = u_right & ~u_sel & ~osd_active;
wire m_up      = u_up    & ~u_sel & ~osd_active;
wire m_down    = u_down  & ~u_sel & ~osd_active;
wire m_a       = u_btn_a & ~osd_active;
wire m_b       = u_btn_b & ~osd_active;
wire m_start1  = u_sta   & ~osd_active;
wire m_start2  = u_btn_x & ~osd_active;
wire m_coin1   = (u_sel & ~osd_active) | key_s2;
// Cabinet-side OSD chord (roadmap item 6): hold the physical coin key
// (AB13 on the bench; the shield's coin-door Service line later) for ~3 s
// to open the game-select menu - identical in every family top. Note: on
// the bench the first 3 s of the hold DO insert a coin (the key doubles as
// Coin 1); the shield build will source this from Service instead, which
// feeds no credits.
reg [26:0] menu_hold_cnt = 27'd0;
wire       menu_hold = (menu_hold_cnt == 27'd120_000_000);   // 3 s @40 MHz
always @(posedge clk_sys) begin
    if (!key_s2)                 menu_hold_cnt <= 27'd0;
    else if (!menu_hold)         menu_hold_cnt <= menu_hold_cnt + 27'd1;
end

wire m_service = 1'b0;

reg [7:0] input_0;
reg [7:0] input_1;
reg [7:0] input_2;
reg [7:0] input_3;
reg [7:0] input_4;

// KICK spinner: the kicker angle is a 4-bit absolute value. Drive it from the
// d-pad Left/Right through the shared spinner and take the low nibble. (A USB
// paddle/mouse could later feed spin_in for a true spinner.) Sensitivity is a
// guess pending hardware play, like the other derived controls.
wire [7:0] kick_spin;
spinner #(.INC_NORMAL(8), .INC_FAST(16), .INC_SPINNER(4)) sp_kick (
    .clk(clk_sys), .reset(core_reset),
    .minus(m_left), .plus(m_right), .fast(1'b0), .strobe(vblank),
    .spin_in(9'd0), .spin_out(kick_spin)
);

always @(*) begin
    input_0 = 8'hFF;
    input_1 = 8'hFF;
    input_2 = 8'hFF;
    input_3 = 8'hFF;   // MCR-1 game-option DIPs; 0xFF = all off (see note)
    input_4 = 8'hFF;
    case (game_id)

    // SOLAR FOX: 4-way stick, mirrored across both nibbles of IP1 (MiSTer maps
    // it to both the P1 and rotated axes). Two fire buttons: fire_a on IP0
    // bit4 and IP2 bit0, fire_b on IP0 bits 3 and 2. Pad: dpad = move, A =
    // fire A, B = fire B.
    GID_SOLARFOX: begin
        input_0 = ~{ m_service, 2'b00, m_a, m_b, m_b, 1'b0, m_coin1 };
        input_1 = ~{ m_up, m_down, m_left, m_right, m_up, m_down, m_left, m_right };
        input_2 = ~{ 7'b0000000, m_a };
    end

    // KICK / KICKMAN (default): spinner (kicker angle) on IP1 low nibble,
    // kick button on IP0 bit 4. Pad: Left/Right = spin, A = kick, Start,
    // Select = coin.
    default: begin
        input_0 = ~{ m_service, 2'b00, m_a, m_start2, m_start1, 1'b0, m_coin1 };
        input_1 = ~{ 4'b0000, kick_spin[3:0] };
    end
    endcase
end

// --- Core Instantiation ---
// (r/g/b/hblank/vblank/hs/vs/cs are declared just before the controls
// section - they are referenced there, and Gowin turns use-before-
// declaration into an implicit 1-bit net with only a warning.)
wire [15:0] audio_l_val, audio_r_val;

wire [9:0] core_hcnt;
wire [9:0] core_vcnt;

mcr1 #(
    // NO BAKED ROMs (licensing): the bitstream must carry no ROM data, so the
    // gfx dprams start blank and the SD pack is the only source. LOADABLE
    // keeps their port B writable - an empty INIT_FILE alone would select
    // dpram's read-only-port-B mode and silently kill the download.
    .GFX1_1_INIT(""), .GFX1_2_INIT(""), .GFX2_INIT(""), .GFX_LOADABLE(1)
) mcr1_core (
    .clock_40(clk_sys),
    .reset(core_reset),

    // Video outputs (4-bit RGB, truncated to 3:3:3 above)
    .video_r(core_r),
    .video_g(core_g),
    .video_b(core_b),
    .video_vblank(vblank),
    .video_hblank(hblank),
    .video_hs(hs),
    .video_vs(vs),
    .video_csync(cs),
    .video_ce(),
    .hcnt_out(core_hcnt),
    .vcnt_out(core_vcnt),

    // 0 = 31kHz scan-doubled progressive (HDMI + VGA monitor),
    // 1 = native 15kHz arcade timing (CRT/scan converter via PmodVGA).
    // Selected by the mode15_n strap on J10.
    .tv15Khz_mode(tv15khz),

    .separate_audio(1'b0), // mono mix
    .audio_out_l(audio_l_val),
    .audio_out_r(audio_r_val),

    .input_0(input_0),
    .input_1(input_1),
    .input_2(input_2),
    .input_3(input_3),
    .input_4(input_4),

    // CPU ROM interface (15-bit addr on MCR-1; read-enable unused)
    .cpu_rom_addr(rom_addr),
    .cpu_rom_do(rom_do),
    .cpu_rom_rd(),
    .snd_rom_addr(snd_addr),
    .snd_rom_do(snd_do),

    .pause(1'b0),
    .flip(1'b0),           // upright; no cocktail screen flip

    // Download interface (fed by the SD loader; inert with no card)
    .dl_addr(dl_addr),
    .dl_wr(dl_wr),
    .dl_data(dl_data),
    .dl_nvram_wr(1'b0),
    .dl_din(),
    .dl_nvram(1'b0)
);

// --- Pixel timing shared by the analog and HDMI paths ----------------------
// One strobe per core pixel: hcnt advances at the 20 MHz pixel rate (every
// other clk_sys cycle).
reg [9:0] hcnt_r;
always @(posedge clk_sys) hcnt_r <= core_hcnt;
wire pixel_tick = (hcnt_r != core_hcnt);

// Compensation for the core's RGB-vs-hcnt pipeline lag, used by BOTH video
// paths (analog sync alignment below, HDMI capture window further down).
// LIVE TUNING: hold Select and tap D-pad Right (+1) / Left (-1) while
// watching the left edge - garbage/overlap on the LEFT means increase.
// Reported in the UART beacon as "dXX"; hardcode the winner below.
localparam [4:0] CAP_DELAY_DEFAULT = 5'd13;
reg [4:0] cap_delay = CAP_DELAY_DEFAULT;
reg tune_l_r = 0, tune_r_r = 0;
always @(posedge clk_sys) begin
    tune_l_r <= u_sel & u_left;
    tune_r_r <= u_sel & u_right;
    if (u_sel & u_left  & ~tune_l_r & (cap_delay != 5'd0))  cap_delay <= cap_delay - 1'b1;
    if (u_sel & u_right & ~tune_r_r & (cap_delay != 5'd31)) cap_delay <= cap_delay + 1'b1;
end

// --- On-screen display (game-select menu) -----------------------------------
// Composited onto the core's RGB *here*, before the video path splits, so
// the menu shows up identically on HDMI, 31 kHz VGA and native 15 kHz.
// Select+Start toggles it; Up/Down move, A reloads from the SD pack, B
// exits. The core raster STOPS while a reload holds the core in reset, so
// expect ~1 s of frozen HDMI frame / dropped VGA sync during a switch.
wire [8:0] osd_rgb;
osd #(
    .GAME_DEFAULT(GAME_DEFAULT),
    // Kickman added 2026-07-27: make_pack_v2 has always packed it at MCR-1
    // slot 2, but NUM_GAMES was 2 so it could not be reached from the menu -
    // only by the SD prefs happening to name slot 2, which is exactly how it
    // turned up on the first hardware run. Roster order must match
    // make_pack_v2's ROSTER: kick(0), solarfox(1), kickman(2).
    .NUM_GAMES(4'd3),
    // All MCR-1 games run on a rotated cabinet monitor (Kick/Kickman =
    // SWAP_XY, Solar Fox = ROT90), so rotate the OSD text for all of them.
    // Flip on hardware if a game reads mirrored (see osd.sv u/v remap note).
    .ROT_MASK(6'b000111),
    .TITLE("    MCR1 GAME SELECT    "),
    .NAME0("   KICK                 "),
    .NAME1("   SOLAR FOX            "),
    .NAME2("   KICKMAN              ")
) osd_inst (
    .clk(clk_sys),
    .rst(core_reset_raw),
    .pixel_tick(pixel_tick),
    .hcnt(core_hcnt),
    .hblank(hblank),
    .vblank(vblank),
    .mode15(tv15khz),
    .rgb_in({r, g, b}),
    .rgb_out(osd_rgb),
    .btn_up(u_up), .btn_down(u_down),
    .btn_a(u_btn_a), .btn_b(u_btn_b),
    .btn_sel(u_sel), .btn_sta(u_sta), .btn_menu_hold(menu_hold),
    .game_id(game_id),
    .load_slot(game_slot),
    .loader_restart(osd_restart),
    .loader_done(ldr_done),
    .loader_error(ldr_error),
    .loaded_slot(ldr_slot),
    .save_req(osd_save),
    .sd_ready(sd_ready),
    .osd_active(osd_active), .osd_nocard(osd_nocard)
);
// Both video paths consume the OSD-composited pixels from here on.
wire [2:0] vid_r = osd_rgb[8:6];
wire [2:0] vid_g = osd_rgb[5:3];
wire [2:0] vid_b = osd_rgb[2:0];

// --- PmodVGA Analog Output (native core timing, zero buffering) ---
// The core's RGB lags its hcnt-derived sync/blank by a fixed pipeline delay
// (tile fetch -> gfx ROM -> palette -> output regs) - the same lag the HDMI
// capture compensates for with cap_delay. Taking hblank/hs raw here let the
// PREVIOUS line's tail leak into the first ~13 visible pixels (a garbled
// strip down the left edge) while blanking swallowed the last 13 real ones.
// Delay the sync/blank signals by the same amount so they line up with the
// pixels they describe. Shares the live-tunable cap_delay: Select + D-pad
// Right/Left adjusts both paths, value shown in the beacon as "dXX".
reg [31:0] hs_sr, vs_sr, cs_sr, hb_sr, vb_sr;
always @(posedge clk_sys) begin
    if (pixel_tick) begin
        hs_sr <= {hs_sr[30:0], hs};
        vs_sr <= {vs_sr[30:0], vs};
        cs_sr <= {cs_sr[30:0], cs};
        hb_sr <= {hb_sr[30:0], hblank};
        vb_sr <= {vb_sr[30:0], vblank};
    end
end
wire [4:0] vga_tap = (cap_delay == 5'd0) ? 5'd0 : cap_delay - 5'd1;
wire hs_d     = (cap_delay == 5'd0) ? hs     : hs_sr[vga_tap];
wire vs_d     = (cap_delay == 5'd0) ? vs     : vs_sr[vga_tap];
wire cs_d     = (cap_delay == 5'd0) ? cs     : cs_sr[vga_tap];
wire hblank_d = (cap_delay == 5'd0) ? hblank : hb_sr[vga_tap];
wire vblank_d = (cap_delay == 5'd0) ? vblank : vb_sr[vga_tap];

// 3:3:3 -> 4:4:4 by MSB replication so full intensity maps to full scale.
// Blank the DAC outside active video so the monitor sees black porches.
wire cab_blank = hblank_d | vblank_d;
assign vga_r = cab_blank ? 4'h0 : {vid_r, vid_r[2]};
assign vga_g = cab_blank ? 4'h0 : {vid_g, vid_g[2]};
assign vga_b = cab_blank ? 4'h0 : {vid_b, vid_b[2]};

// Sync format. 31 kHz always uses separate negative H/V (standard RGBHV).
//
// 15 kHz also defaults to SEPARATE H and V sync, for two reasons: it is what
// a real MCR cabinet expects (the Video connector has discrete H-Sync on
// pin 8 and V-Sync on pin 9), and modern 15 kHz-capable displays detect it
// reliably. Composite sync was the old default and cost a long debug session
// - one LCD silently dropped its entire green channel, apparently deciding a
// csync source must carry sync-on-green and clamping that input. Note such
// displays latch their format detection, so a wrong guess persists until
// sync is disturbed; changing format while running may not re-trigger it.
//
// Strap J10-39 to GND for composite sync on HS instead (RGBS - what an
// OSSC/RetroTink or an SOG-wired monitor may prefer).
// Strap J10-40 to GND to hold VS inactive (pure single-sync RGBS).
wire want_csync = ~map_rows_n;   // J10-39 to GND
wire vsync_off  = ~map_sock_n;   // J10-40 to GND

assign vga_hs = (tv15khz && want_csync) ? cs_d : hs_d;
assign vga_vs = vsync_off ? 1'b1 : vs_d;

// --- PmodVGA plugged directly into the PMOD sockets --------------------------
// Sipeed socket columns (anchored at the power end, which mates with the
// Pmod's VCC/GND columns): [3V3][GND][IO6/7][IO4/5][IO2/3][IO0/1].
// Digilent columns from the same end: [VCC][GND][4/10][3/9][2/8][1/7].
// => forced column pairing: Pmod pins {1,2,3,4} land on even-or-odd IOs
// {0,2,4,6} and pins {7,8,9,10} on the other row - which row is which, and
// which socket meets PmodVGA J1 (R/B) vs J2 (G/sync), depends on physical
// orientation we can't see in the schematic. Both unknowns are runtime
// straps: try the 4 combinations, exactly one shows a stable picture.
wire row_swap  = ~map_rows_n;   // strap to GND to swap rows
wire sock_swap = ~map_sock_n;   // strap to GND to swap sockets

// Socket carrying PmodVGA J1 (R + B ladders)
wire [7:0] j1_rows_a = {vga_b[3], vga_r[3], vga_b[2], vga_r[2],
                        vga_b[1], vga_r[1], vga_b[0], vga_r[0]}; // IO7..IO0
wire [7:0] j1_rows_b = {vga_r[3], vga_b[3], vga_r[2], vga_b[2],
                        vga_r[1], vga_b[1], vga_r[0], vga_b[0]};
wire [7:0] j1_bus = row_swap ? j1_rows_b : j1_rows_a;

// Socket carrying PmodVGA J2 (G ladder + HS/VS; Pmod pins 9/10 are NC)
wire [7:0] j2_rows_a = {1'b0, vga_g[3], 1'b0, vga_g[2],
                        vga_vs, vga_g[1], vga_hs, vga_g[0]};     // IO7..IO0
wire [7:0] j2_rows_b = {vga_g[3], 1'b0, vga_g[2], 1'b0,
                        vga_g[1], vga_vs, vga_g[0], vga_hs};
wire [7:0] j2_bus = row_swap ? j2_rows_b : j2_rows_a;

assign pmod0_io = sock_swap ? j2_bus : j1_bus;
assign pmod1_io = sock_swap ? j1_bus : j2_bus;

// --- HDMI Output: DDR3 framebuffer -> 1280x720@60 (nand2mario/gbatang) ------
// The core streams its native 512x480 image into a DDR3-backed framebuffer,
// which upscales to 720p (game shown 960 wide for 4:3) and drives HDMI with
// audio. This fully decouples core and display timing: no line buffer, no
// genlock, no shimmer. In 15 kHz mode the capture height drops to 240 lines
// per field and the upscaler adapts (integer 3x).

// The core's RGB output lags its hcnt by a fixed pipeline delay (tile fetch ->
// gfx ROM -> palette -> output regs); shift the capture window back by
// cap_delay so each line's pixels land at the right offsets.
// LIVE TUNING: hold Select and tap D-pad Right (+1) / Left (-1) while
// watching the left edge - garbage/overlap on the LEFT means increase.
// The current value is reported in the UART beacon as "dXX" (hex); once the
// sweet spot is found, hardcode it as the reset value below.
// (The D-pad is masked from the game while Select is held; note Select
// itself still inserts a coin - harmless during tuning.)


wire cap_active = !vblank && (core_hcnt >= {5'b0, cap_delay}) && (core_hcnt < {5'b0, cap_delay} + 10'd512);
wire fb_we = pixel_tick && cap_active;
// RGB444: replicate each 3-bit channel's MSB into bit 0 (as the VGA DAC does)
wire [11:0] fb_data = {vid_r, vid_r[2], vid_g, vid_g[2], vid_b, vid_b[2]};

// Single-cycle frame pulse after the last active line (vblank rising edge)
reg fb_vbl_r = 1'b1;
always @(posedge clk_sys) fb_vbl_r <= vblank;
wire fb_vsync = vblank & ~fb_vbl_r;

// DDR3/HDMI bring-up debug on spare J10 pins (probe vs GND with a DMM):
//   debug_o[0] J10-21: init_calib_complete - steady 3.3V = DDR3 trained
//   debug_o[1] J10-22: ~1.1Hz heartbeat from clk_x1 (74.25MHz pixel clock)
//   debug_o[2] J10-23: ~0.8Hz heartbeat from the 27MHz reference
//   debug_o[3] J10-24: ddr_rst - should sit LOW once the DDR PLL settles
wire fb_clk_x1, fb_ddr_rst, fb_calib;
wire fb_hclk;             // HDMI pixel clock (74.25 MHz expected)
// NOTE: do not hang a counter on hclk5 (371 MHz). It is unconstrained in the
// SDC, so the tool cannot see the speed, and the added logic disturbed the
// DDR3 interface enough to stop it calibrating (beacon showed c0). hclk5 was
// measured this way once and confirmed at 5x hclk; that is enough.
reg [24:0] hb_h = 0;
always @(posedge fb_hclk) hb_h <= hb_h + 1'b1;
reg [25:0] hb_x1 = 0;
reg [24:0] hb_27 = 0;
always @(posedge fb_clk_x1) hb_x1 <= hb_x1 + 1'b1;
always @(posedge clk27)     hb_27 <= hb_27 + 1'b1;
assign debug_o = {fb_ddr_rst, hb_27[24], hb_x1[25], fb_calib};

// Same vitals over USB-C serial (BL616 bridges the U15 UART), for debugging
// with the case closed: frozen x____ across lines = pixel clock dead,
// frozen q__ = 27MHz chain dead, c0/r1 = DDR3 never trained.
uart_beacon #(.CLK_HZ(40_000_000), .BAUD(115200)) beacon (
    .clk(clk_sys),
    .calib(fb_calib),
    .ddr_rst(fb_ddr_rst),
    .cnt_x({hb_h[24:21], hb_x1[25:14]}),
    .cnt_q(hb_27[24:17]),
    .aux({game_id, cap_delay}),   // dXX: high 3 bits = running game_id
    // L high nibble: {heartbeat, heartbeat, usb_typ} - usb_typ = 3 means a
    // gamepad is enumerated (0 = nothing on USB); low nibble = SD/loader.
    .aux2({hb_h[24:23], usb_typ_s2, sd_ready, sd_err, ldr_done, ldr_error}),
    .txd(uart_tx)
);

ddr3_framebuffer #(
    .WIDTH(512),
    .HEIGHT(480),
    .COLOR_BITS(12),
    .PREFETCH_DELAY(44),
    .DVI_MODE(0)          // full HDMI, as NESTang uses
) fb_inst (
    .hclk_dbg(fb_hclk),
    .clk_27(clk27),
    .pll_lock_27(1'b1),
    .clk_g(clk50_pll),        // PLL-buffered 50 MHz (global clock net)
    .clk_out(fb_clk_x1),
    // Reset from the power-on counter ONLY - never from rom_ready. Video must
    // come up independently of ROM loading, otherwise a stalled/slow SD load
    // takes HDMI sync down with it and there is nothing to diagnose from.
    .rst_n(~core_reset_raw),
    .ddr_rst(fb_ddr_rst),
    .init_calib_complete(fb_calib),
    .ddr_prefetch_delay(6'd44),

    // Framebuffer write interface (core pixel stream)
    .clk(clk_sys),
    .fb_width(11'd512),
    .fb_height(tv15khz ? 10'd240 : 10'd480),
    .disp_width(11'd960),     // 4:3 within the 720p canvas
    .fb_vsync(fb_vsync),
    .fb_we(fb_we),
    .fb_data(fb_data),

    // HDMI audio (offset-binary core mix -> signed PCM)
    .sound_left(audio_l_val ^ 16'h8000),
    .sound_right(audio_r_val ^ 16'h8000),

    // DDR3 (on-SOM 4Gb x16)
    .ddr_addr(ddr_addr),
    .ddr_bank(ddr_bank),
    .ddr_cs(ddr_cs),
    .ddr_ras(ddr_ras),
    .ddr_cas(ddr_cas),
    .ddr_we(ddr_we),
    .ddr_ck(ddr_ck),
    .ddr_ck_n(ddr_ck_n),
    .ddr_cke(ddr_cke),
    .ddr_odt(ddr_odt),
    .ddr_reset_n(ddr_reset_n),
    .ddr_dm(ddr_dm),
    .ddr_dq(ddr_dq),
    .ddr_dqs(ddr_dqs),
    .ddr_dqs_n(ddr_dqs_n),

    // HDMI out
    .tmds_clk_n(tmds_clk_n),
    .tmds_clk_p(tmds_clk_p),
    .tmds_d_n(tmds_d_n),
    .tmds_d_p(tmds_d_p)
);

// --- PWM Audio Modulators ---
ds_dac dac_l (
    .clk(clk_sys),
    .resetn(~core_reset),
    .din(audio_l_val),
    .dout(audio_l)
);

ds_dac dac_r (
    .clk(clk_sys),
    .resetn(~core_reset),
    .din(audio_r_val),
    .dout(audio_r)
);

endmodule
