// game_config.vh is generated by `python3 tools/merge_roms.py <game>`;
// for MCR-3 it defines GAME_TAPPER (etc.) to select the input/DIP mapping.
`include "game_config.vh"

// Tang Console 60K top for the MCR-3 (91490) Arcade Core. This is the MCR-2
// top with the core swapped for src/rtl/mcr3.vhd; the shared platform (PLL,
// DDR3 framebuffer/HDMI, analog video, USB, OSD, beacon, audio) is
// identical. MCR-3 INCREMENT 0 (this build): CPU/sound/bg baked in BSRAM
// like MCR-1/2, and the 128 KB sprite ROM is NOT yet wired - sp_graphx32_do
// is tied to 0, so sprites render blank. This proves the core + CPU +
// background + video pipeline on our platform. INCREMENT 1 adds the SDRAM
// sprite path (sdram_gw sp port at 80 MHz) + the SD->SDRAM sprite loader.
module mcr3_console60k_top (
    input        sys_clk,       // 50 MHz on-board oscillator (pin V22)
    input        s1,            // User key AA13 - ACTIVE LOW on console (pull-up)
    input        reset2,        // User key AB13 - ACTIVE LOW on console (pull-up)

    // DVI/HDMI output.
    // hpd_en drives the dock's HDMI enable. Sipeed's own NEO_DOCK example
    // drives this pin at DRIVE=12; nand2mario's cores leave it unassigned
    // (tri-stated with a weak internal pull-up), which is what we did too.
    // If the net has an external pull-down, that weak pull-up loses and the
    // dock's HDMI stays disabled - and because JTAG reconfiguration does not
    // power-cycle the board, whether a previous core left the line high can
    // decide if a picture appears. Drive it explicitly.
    output       hpd_en,
    output       tmds_clk_p,
    output       tmds_clk_n,
    output [2:0] tmds_d_p,
    output [2:0] tmds_d_n,

    // On-SOM DDR3 (framebuffer backing store; pins from gbatang console60k)
    output [14:0] ddr_addr,
    output [2:0]  ddr_bank,
    output        ddr_cs,
    output        ddr_ras,
    output        ddr_cas,
    output        ddr_we,
    output        ddr_ck,
    output        ddr_ck_n,
    output        ddr_cke,
    output        ddr_odt,
    output        ddr_reset_n,
    output [1:0]  ddr_dm,
    inout  [15:0] ddr_dq,
    inout  [1:0]  ddr_dqs,
    inout  [1:0]  ddr_dqs_n,

    // PMOD sockets, repurposed to host the Digilent PmodVGA directly.
    // (Desk buttons retired - inputs come from the USB pad and board keys.)
    // Sipeed socket IO order differs from Digilent pin order; the physical
    // row/socket orientation is resolved at runtime by the two map_* straps.
    output [7:0] pmod0_io,
    output [7:0] pmod1_io,
    input        map_rows_n,     // J10-39 strap: open/GND = try both
    input        map_sock_n,     // J10-40 strap: open/GND = try both

    // Digilent PmodVGA (4:4:4 + HS/VS) wired to J10 header - see CST for the
    // jumper recipe. Analog output has no line buffer -> no shimmer/tearing.
    output [3:0] vga_r,
    output [3:0] vga_g,
    output [3:0] vga_b,
    output       vga_hs,
    output       vga_vs,

    // 15/31 kHz select strap on J10 (internal pull-up):
    // open = 31 kHz progressive (VGA monitor), jumper to GND = 15 kHz
    // native arcade timing (CRT / OSSC / RetroTink; VGA LCDs will not sync)
    input        mode15_n,

    // USB-A port 1 (left) - USB HID host (15k pulldowns are on the board)
    inout        usb1_dp,
    inout        usb1_dn,

    // MicroSD card (SPI mode) - optional ROM source, see rom_loader.sv
    output       sd_clk,
    output       sd_cmd,      // MOSI
    input        sd_dat0,     // MISO
    output       sd_dat3,     // CS

    // DDR3/HDMI bring-up debug (J10 pins 21-24; see comment at the logic)
    output [3:0] debug_o,

    // Status beacon on the FPGA->BL616 UART (shows up as USB-C serial,
    // 115200 8N1): one "FB c_ r_ x____ q__" line every ~0.5s
    output       uart_tx,

    // PWM Audio output
    output       audio_l,
    output       audio_r,

    // Tang SDRAM module (J9) - holds the 128 KB sprite ROM (too big for BSRAM).
    // Pins from the verified sdram_memtest.cst (nand2mario snestang layout);
    // CKE is tied high on the module (no FPGA pin). Bank is 3.3V (these balls
    // are NOT in the DDR3's bank 9), so LVCMOS33 coexists with the framebuffer.
    inout  [15:0] O_sdram_dq_io,
    output [12:0] O_sdram_addr,
    output [1:0]  O_sdram_ba,
    output [1:0]  O_sdram_dqm,
    output        O_sdram_clk,
    output        O_sdram_cs_n,
    output        O_sdram_wen_n,
    output        O_sdram_ras_n,
    output        O_sdram_cas_n
);

assign hpd_en = 1'b1;   // enable the dock's HDMI path

// --- Clock Generation ---
// gowin_pll_core80 (60K/MCR-3 variant, VCO=800): drops the unused 125 MHz TMDS
// clock and adds clk_sdram = 80 MHz = 2x clk_sys, phase-locked off the same VCO
// so the SDRAM sprite read is a synchronous 1:2 crossing to the 40 MHz core.
wire clk_sys;    // 40 MHz  (Core system clock, generates 20 MHz pixel enable)
wire clk_sdram;  // 80 MHz  (SDRAM controller, synchronous 2x clk_sys)
wire pll_locked;

wire clk50_pll;  // PLL-buffered 50 MHz for the DDR3 controller/mDRP (clk_g).
                 // Feeding the raw pad clock there put a derived clock on
                 // generic routing (PR1014) and the DDR3 IP never came up.
gowin_pll_core80 pll_inst (
    .clkin(sys_clk),
    .clk_sys(clk_sys),
    .clk_sdram(clk_sdram),
    .clk_50(clk50_pll),
    .lock(pll_locked)
);

// 27 MHz reference for the DDR3 framebuffer's internal PLLs (720p + DDR3)
wire clk27;
pll_27 pll27_inst (
    .clkin(sys_clk),
    .clkout0(clk27)
);

// Second PLLA: 50 MHz -> exactly 12 MHz for the USB HID host
// (VCO = 50*18 = 900 MHz, ODIV0 = 75; config from nand2mario's usb_hid_host)
wire clk_usb;
gowin_pll_usb pll_usb_inst (
    .clkin(sys_clk),
    .clkout(clk_usb)
);

// --- Reset Generation ---
// Unlike the Primer 25K (buttons active high w/ pulldown), the Tang Console's
// user keys are active LOW with pull-ups. Invert once here; the rest of the
// design keys off the active-high key_s1/key_s2 exactly like the 25K top.
wire key_s1 = ~s1;
wire key_s2 = ~reset2;

// 15 kHz strap, synchronized into the core clock domain (active low pin).
// Live toggling works; if the picture is disturbed after moving the jumper,
// press S1 (reset) once.
reg mode15_s1 = 0, mode15_s2 = 0;
always @(posedge clk_sys) begin
    mode15_s1 <= ~mode15_n;
    mode15_s2 <= mode15_s1;
end
wire tv15khz = mode15_s2;

// (Video note: the DDR3 framebuffer captures whatever timing the core emits,
// so HDMI stays alive in 15 kHz mode too - capture height drops to 240
// lines per field and the upscaler adapts.)

reg [7:0] reset_cnt = 255;
wire      rom_ready;                          // ROM image settled
wire core_reset_raw = (reset_cnt != 0);       // resets the SD loader itself

// core_reset is REGISTERED: it fans out to every synchronous reset in the
// core, and as a combinational function of reset_cnt it became the critical
// path (deterministic -0.35ns on the shollow build). One extra cycle of
// reset latency costs nothing.
reg core_reset = 1'b1;
always @(posedge clk_sys) core_reset <= core_reset_raw || !rom_ready;

// Game selection. game_id picks the input/DIP mapping at RUNTIME (all six
// maps are compiled in); game_slot tells the SD loader which pack slot to
// (re)load. Both are owned by the OSD menu (Select+Start on the pad).
// The power-on default is whatever game merge_roms.py baked into BSRAM, so
// map and ROMs always match at boot - with or without a card.
// Slot order = tools/merge_roms.py GAME_SPECS order (= the pack's order).
// MCR-3 roster (Increment 0: Tapper only). Timber/Journey/DoT slot in later.
localparam [2:0] GAME_DEFAULT = 3'd0;   // Tapper

wire [2:0] game_id;      // game the core is running (from the OSD)
wire [3:0] game_slot;    // SD pack slot the loader (re)loads
wire       osd_restart;  // OSD pulse: restart the loader with game_slot
wire       osd_active;   // menu open -> game inputs masked below

always @(posedge clk_sys) begin
    if (key_s1 || !pll_locked) begin
        reset_cnt <= 255;
    end else if (reset_cnt != 0) begin
        reset_cnt <= reset_cnt - 8'd1;
    end
end

// --- ROM source ---------------------------------------------------------
// The INIT_FILE contents are the power-on default (whatever game
// `merge_roms.py` last generated - Tron by default), so the board always
// boots something even with no SD card. When a card holding a valid pack is
// present, rom_loader overwrites these memories before the core leaves
// reset and the DIP-selected game runs instead.
wire        sd_ready, sd_err, sd_rd_start, sd_rd_done, sd_dv;
wire [7:0]  sd_dout;
wire [31:0] sd_sector;
wire        sd_wr_start, sd_wr_next, sd_wr_done;
wire [7:0]  sd_wr_din;
wire [16:0] dl_addr;
wire [7:0]  dl_data;
wire        dl_wr;
wire        ldr_done, ldr_error, ldr_saved;
wire [3:0]  ldr_slot;      // slot actually loaded (SD-saved pref at boot)
wire        osd_save;      // OSD: persist the selection to the prefs sector

// Core runs once the loader has finished, or as soon as it gives up on a
// missing/unreadable card (then the baked-in ROMs stand).
assign rom_ready = ldr_done | ldr_error;

// ldr_sd_rst lets the loader force a full card re-init between retries;
// sd_reader latches `err`, so without it a transient failure (e.g. the card
// left mid-command by JTAG reconfiguration) could never be cleared.
wire ldr_sd_rst;

sd_reader #(.CLK_HZ(40_000_000)) sd (
    .clk(clk_sys), .rst(core_reset_raw | ldr_sd_rst),
    .ready(sd_ready), .err(sd_err),
    .rd_start(sd_rd_start), .rd_sector(sd_sector),
    .dout(sd_dout), .dout_valid(sd_dv), .rd_done(sd_rd_done),
    .wr_start(sd_wr_start), .wr_din(sd_wr_din),
    .wr_next(sd_wr_next), .wr_done(sd_wr_done), .wr_err(),
    .sclk(sd_clk), .mosi(sd_cmd), .miso(sd_dat0), .cs_n(sd_dat3)
);

// MAX_RETRY raised: MCR-3 sprites live on the card, so a boot that gives up
// early renders white/garbage sprites rather than degrading gracefully.
rom_loader #(.PACK_BASE(32'd2048), .SLOT_SECTORS(256), .MAX_RETRY(3'd7)) loader (
    .clk(clk_sys), .rst(core_reset_raw | osd_restart),
    .slot(game_slot),
    // Boot consults the SD-saved preference; an OSD-commanded reload
    // (menu open) loads exactly the slot the user picked.
    .use_prefs(~osd_active),
    .save_req(osd_save), .saved(ldr_saved),
    .cur_slot(ldr_slot),
    .sd_ready(sd_ready), .sd_err(sd_err), .sd_rst(ldr_sd_rst),
    .sd_rd_start(sd_rd_start), .sd_sector(sd_sector),
    .sd_dout(sd_dout), .sd_dout_valid(sd_dv), .sd_rd_done(sd_rd_done),
    .sd_wr_start(sd_wr_start), .sd_wr_din(sd_wr_din),
    .sd_wr_next(sd_wr_next), .sd_wr_done(sd_wr_done),
    .dl_addr(dl_addr), .dl_data(dl_data), .dl_wr(dl_wr),
    .done(ldr_done), .error(ldr_error)
);

// Phase 1 (sprites-first): CPU/sound/bg stay BAKED in BSRAM (INIT_FILE); the
// SD pack holds ONLY the 128 KB sprite blob, and the whole dl stream is routed
// to SDRAM below. So the CPU/sound dl-write ports are held off here (a sprite
// byte at dl_addr < 0x10000 must NOT land in the CPU ROM), and the core's
// dl_wr is tied low (its bg dl-decode must not overwrite the baked bg).
wire cpu_rom_we = 1'b0;
wire snd_rom_we = 1'b0;

// ------------------------------------------------------------------------
// Sprite SDRAM (Tang module, J9): read port to the core + write port from the
// SD loader. sdram_gw is the MiSTer MCR-3 controller (verified by the memtest
// at 100 MHz); here it runs at clk_sdram = 80 MHz = 2x the 40 MHz core.
// ------------------------------------------------------------------------
wire [14:0] core_sp_addr;   // core -> SDRAM: 15-bit sprite word address
wire [31:0] sp_q;           // SDRAM -> core: 32-bit (4-plane) sprite word

// The loader streams the 128 KB sprite blob as dl_addr[16:0]/dl_data on
// clk_sys. Route it to SDRAM *port2* with MiSTer's exact sprite write-swizzle
// (Arcade-MCR3.sv). port2 is REQUIRED (not port1): the sp read port lives in
// the controller's bank 2,3 group, and only port2 writes into that same group
// - a port1 write lands in banks 0,1 and the sprite read never sees it (the
// "solid white boxes" symptom). The swizzle merges the 8 concatenated planes
// into 32-bit words so a linear sp_addr read returns the 4 planes per column:
//   port2_a  = {7'b0, dl_addr[14:0], dl_addr[16]}   (16-bit word address)
//   port2_ds = {dl_addr[15], ~dl_addr[15]}          (which byte of the word)
//   port2_d  = {dl_data, dl_data}                   (ds picks the lane)
// clk_sdram = 2x clk_sys (synchronous), so dl_wr is a 2-cycle pulse here;
// rising-edge detect turns each into exactly one port2 write. The SD byte rate
// is << clk_sdram, so a write always finishes before the next dl_wr.
wire        p1_ack;
wire [23:0] dbg_refresh;    // DIAGNOSTIC: AUTO_REFRESH issue counter (24b, see sdram_gw)
wire [15:0] dbg_blk0, dbg_blk1; // DIAGNOSTIC: refresh-demand blocker counters
// DIAGNOSTIC: refresh RATE over a fixed 2^23-cycle window (~104.9 ms @80MHz).
// A free-running counter sampled by the beacon aliases hopelessly at 133k/s:
// dividing it by 256 did not change the observed rate, which proves the
// sampling - not the signal - set that number. A per-window latched count
// cannot wrap. Healthy = 133333*0.1049 = ~13976 (0x3698);
// starved-at-2325/s would be ~244 (0x00F4). Read in beacon slot E1.
reg [22:0] rw_div = 23'd0;
reg [15:0] rw_cnt = 16'd0, rw_lat = 16'd0;
reg        rw_d   = 1'b0;
always @(posedge clk_sdram) begin
    rw_div <= rw_div + 1'b1;
    rw_d   <= dbg_refresh[0];            // bit0 toggles once per AUTO_REFRESH
    if (dbg_refresh[0] != rw_d) rw_cnt <= rw_cnt + 1'b1;
    if (&rw_div) begin rw_lat <= rw_cnt; rw_cnt <= 16'd0; end
end

reg         sdram_rst_s1 = 1'b1, sdram_rst = 1'b1;
always @(posedge clk_sdram) begin
    sdram_rst_s1 <= core_reset_raw;
    sdram_rst    <= sdram_rst_s1;
end

reg        dl_wr_s1 = 1'b0, dl_wr_s2 = 1'b0;
reg        ldrp_s1 = 1'b0, ldrp_s2 = 1'b0;  // ldr_done sync for the pattern writer
reg [4:0]  pat_step = 5'd31;                // 31 = idle, 0..15 = write steps
reg [4:0]  pat_wait = 5'd0;
reg        p1_req_r = 1'b0, p1_we_r = 1'b0;
reg [23:1] p1_a_r = 23'd0;
reg [1:0]  p1_ds_r = 2'b00;
reg [15:0] p1_d_r = 16'd0;
// DIAGNOSTIC (temporary): count sprite writes issued + flag if sp_q ever reads
// something other than all-ones. Surfaced in the beacon to localize the
// still-white-boxes fault (write not issued? not landing? read stuck?).
reg [23:0] spw_count = 24'd0;
reg        spq_nonff = 1'b0;
always @(posedge clk_sdram) begin
    dl_wr_s1 <= dl_wr;
    dl_wr_s2 <= dl_wr_s1;
    if (dl_wr_s1 && !dl_wr_s2) begin        // rising edge of a new dl byte
        p1_a_r    <= {7'b0, dl_addr[14:0], dl_addr[16]};
        p1_ds_r   <= {dl_addr[15], ~dl_addr[15]};
        p1_d_r    <= {dl_data, dl_data};
        p1_we_r   <= 1'b1;
        p1_req_r  <= ~p1_req_r;             // launch (toggle req vs ack)
        spw_count <= spw_count + 24'd1;
    end
    // DIAGNOSTIC (temporary): after each load finishes, overwrite the top 4
    // sprite words (0x7FC0-0x7FC3) with a known byte pattern via the same
    // port2 path (16 single-byte writes, one per lane). The repeating dump
    // below watches these cells: correct at first read then rotting = decay
    // (refresh dead); wrong from the start = the write path itself.
    // Expected readback: word k = {C3,C2,C1,C0} + k*04040404 (k = 0..3).
    ldrp_s1 <= ldr_done;
    ldrp_s2 <= ldrp_s1;
    if (ldrp_s1 && !ldrp_s2) begin
        pat_step <= 5'd0;
        pat_wait <= 5'd0;
    end else if (pat_step != 5'd31) begin
        pat_wait <= pat_wait + 5'd1;
        if (&pat_wait) begin                // one write every 32 cycles
            p1_a_r   <= {7'b0, (15'h7FC0 | {13'd0, pat_step[3:2]}), pat_step[1]};
            p1_ds_r  <= pat_step[0] ? 2'b10 : 2'b01;
            p1_d_r   <= {2{8'hC0 | {4'd0, pat_step[3:0]}}};
            p1_we_r  <= 1'b1;
            p1_req_r <= ~p1_req_r;
            pat_step <= (pat_step == 5'd15) ? 5'd31 : pat_step + 5'd1;
        end
    end
    if (sp_q != 32'hFFFFFFFF) spq_nonff <= 1'b1;
end
// DIAGNOSTIC (temporary): after each completed load, sweep all 32K sprite
// words back through the sp read port with a 64-cycle dwell per address
// (~8x the worst-case read latency, so the value sampled is unquestionably
// settled) and classify each word. Separates bad *storage* (a DQM byte lane
// never written -> a lane counter pegs near 32768) from bad *fetch timing*
// during rendering (all counters ~0 here, yet stripes on screen). Sprites
// render garbage for the ~26 ms the sweep steals the sp address bus.
// Byte lanes: sp_q bytes 0,2 came through DQML; bytes 1,3 through DQMH.
reg        ldrd_s1 = 1'b0, ldrd_s2 = 1'b0;
reg        chk_active = 1'b0, chk_done = 1'b0;
reg [14:0] chk_addr = 15'd0;
reg [5:0]  chk_dwell = 6'd0;
reg [15:0] chk_allff = 16'd0;  // words entirely 0xFFFFFFFF
reg [15:0] chk_loff  = 16'd0;  // words with both DQML lanes 0xFF (not all-FF)
reg [15:0] chk_hoff  = 16'd0;  // words with both DQMH lanes 0xFF (not all-FF)
always @(posedge clk_sdram) begin
    ldrd_s1 <= ldr_done;
    ldrd_s2 <= ldrd_s1;
    if (ldrd_s1 && !ldrd_s2) begin
        // EXPERIMENT: sweep DISABLED (it pre-reads every address, which is
        // itself suspected of killing rows). chk_done still set so the dump
        // triggers; counters stay 0.
        chk_done <= 1'b1;
    end else if (chk_active) begin
        chk_dwell <= chk_dwell + 6'd1;
        if (chk_dwell == 6'd63) begin
            if (sp_q == 32'hFFFFFFFF)
                chk_allff <= chk_allff + 16'd1;
            else if (sp_q[7:0] == 8'hFF && sp_q[23:16] == 8'hFF)
                chk_loff <= chk_loff + 16'd1;
            else if (sp_q[15:8] == 8'hFF && sp_q[31:24] == 8'hFF)
                chk_hoff <= chk_hoff + 16'd1;
            chk_addr <= chk_addr + 15'd1;
            if (chk_addr == 15'h7FFF) begin
                chk_active <= 1'b0;
                chk_done   <= 1'b1;
            end
        end
    end
end

// sample the clk_sdram diagnostics into clk_sys for the beacon (synchronous)
reg [23:0] spw_count_s = 0;
reg        spq_nonff_s = 0;
reg [15:0] chk_allff_s = 0, chk_loff_s = 0, chk_hoff_s = 0;
reg        chk_done_s = 0;
reg [23:0] dbg_refresh_s = 0;
reg [15:0] dbg_blk0_s = 0, dbg_blk1_s = 0;
reg [15:0] rw_lat_s = 0;
always @(posedge clk_sys) begin
    spw_count_s <= spw_count;
    spq_nonff_s <= spq_nonff;
    chk_allff_s <= chk_allff;
    chk_loff_s  <= chk_loff;
    chk_hoff_s  <= chk_hoff;
    chk_done_s  <= chk_done;
    dbg_refresh_s <= dbg_refresh;
    dbg_blk0_s <= dbg_blk0;
    dbg_blk1_s <= dbg_blk1;
    rw_lat_s   <= rw_lat;
end

// DIAGNOSTIC (temporary): repeating windowed dump of the sprite SDRAM over
// the UART. Every ~1.7 s it prints a snapshot: a "========" marker line then
// 136 words as 8-hex + LF (~106 ms of TX, beacon muxed away meanwhile):
//   lines   0..63  = sprite words 0x0000-0x003F  (read all-FF in dump #1)
//   lines  64..127 = sprite words 0x2780-0x27BF  (the dump-#1 survivor region)
//   lines 128..135 = sprite words 0x7FC0-0x7FC7  (0x7FC0-3 = the known
//                    pattern the post-load writer plants; expect
//                    C3C2C1C0 C7C6C5C4 CBCAC9C8 CFCECDCC)
// Watching the SAME cells across snapshots separates decay (refresh dead:
// correct -> rot) from a broken write path (wrong from snapshot #1).
localparam DUMP_DIV = 40_000_000 / 115200;   // 347, same baud as the beacon
function [7:0] dump_hex(input [3:0] n);
    dump_hex = (n < 10) ? (8'h30 + n) : (8'h41 + n - 10);
endfunction
reg        dump_active = 1'b0, dump_started = 1'b0;
reg        dump_sampling = 1'b0;
reg        dump_marker = 1'b0;
// EXPERIMENT layout: 20 probe cells x 3 lines each (read1, dummy-address
// read to force a fresh activation, read2 of the same cell ~1.7 ms later).
// Probes 0..15 = 0x2780+j (loaded data), 16..19 = 0x7FC0+k (planted
// pattern). read1 == expected but read2 == FF proves the array holds data
// until it is ACCESSED - a destructive-read / refresh-collision fault, not
// leak decay. Both reads FF from the start = the write path never landed it.
reg [4:0]  dump_j  = 5'd0;      // which probe cell (0..19)
reg [1:0]  dump_ph = 2'd0;      // 0 = read1, 1 = dummy, 2 = read2
reg [23:0] dump_gap = 24'd0;    // ~0.42 s between snapshots
reg [5:0]  dump_wait = 6'd0;
reg [8:0]  dump_baud = 9'd0;
reg [3:0]  dump_bit  = 4'd0;    // 0 = start, 1..8 = data, 9 = stop
reg [3:0]  dump_char = 4'd0;    // 0..7 = hex nibbles MSB-first, 8 = LF
reg [31:0] dump_word = 32'd0;
reg        dump_txd = 1'b1;
wire [14:0] dump_base = (dump_j < 5'd16) ? (15'h2780 + {10'd0, dump_j})
                                         : (15'h7FC0 + {13'd0, dump_j[1:0]});
wire [14:0] dump_a = (dump_ph == 2'd1) ? (15'h0400 + {10'd0, dump_j}) : dump_base;
wire [7:0] dump_cur = (dump_char == 4'd8) ? 8'h0A :
                      dump_marker         ? "="   : dump_hex(dump_word[31:28]);
always @(posedge clk_sys) begin
    if (!dump_active) begin
        dump_txd <= 1'b1;
        dump_gap <= dump_gap + 24'd1;
        // first snapshot right after the load completes, then periodic
        if ((!dump_started && chk_done_s) || (dump_started && (&dump_gap))) begin
            dump_started  <= 1'b1;
            dump_active   <= 1'b1;
            dump_marker   <= 1'b1;      // snapshot starts with a marker line
            dump_sampling <= 1'b0;
            dump_j        <= 5'd0;
            dump_ph       <= 2'd0;
            dump_char     <= 4'd0;
            dump_bit      <= 4'd0;
            dump_baud     <= 9'd0;
        end
    end else if (dump_sampling) begin
        // hold the address for 64 clk_sys cycles (>> read latency), then latch
        dump_txd  <= 1'b1;
        dump_wait <= dump_wait + 6'd1;
        if (dump_wait == 6'd63) begin
            dump_word     <= sp_q;
            dump_sampling <= 1'b0;
            dump_char     <= 4'd0;
            dump_bit      <= 4'd0;
            dump_baud     <= 9'd0;
        end
    end else begin
        if (dump_baud == DUMP_DIV - 1) begin
            dump_baud <= 9'd0;
            if (dump_bit == 4'd9) begin
                dump_bit <= 4'd0;
                if (dump_char == 4'd8) begin        // line finished
                    if (dump_marker) begin
                        dump_marker   <= 1'b0;      // marker done -> first read
                        dump_sampling <= 1'b1;
                        dump_wait     <= 6'd0;
                    end else if (dump_j == 5'd19 && dump_ph == 2'd2) begin
                        dump_active <= 1'b0;        // snapshot done
                        dump_gap    <= 24'd0;
                    end else begin
                        if (dump_ph == 2'd2) begin
                            dump_ph <= 2'd0;
                            dump_j  <= dump_j + 5'd1;
                        end else begin
                            dump_ph <= dump_ph + 2'd1;
                        end
                        dump_sampling <= 1'b1;
                        dump_wait     <= 6'd0;
                    end
                end else begin
                    dump_char <= dump_char + 4'd1;
                    dump_word <= dump_word << 4;
                end
            end else begin
                dump_bit <= dump_bit + 4'd1;
            end
        end else begin
            dump_baud <= dump_baud + 9'd1;
        end
        case (dump_bit)
            4'd0:    dump_txd <= 1'b0;
            4'd9:    dump_txd <= 1'b1;
            default: dump_txd <= dump_cur[dump_bit - 4'd1];
        endcase
    end
end

sdram_gw #(.RFRSH_CYCLES(10'd600)) sdram (
    .SDRAM_DQ(O_sdram_dq_io),
    .SDRAM_A(O_sdram_addr),
    .SDRAM_DQML(O_sdram_dqm[0]),
    .SDRAM_DQMH(O_sdram_dqm[1]),
    .SDRAM_BA(O_sdram_ba),
    .SDRAM_nCS(O_sdram_cs_n),
    .SDRAM_nWE(O_sdram_wen_n),
    .SDRAM_nRAS(O_sdram_ras_n),
    .SDRAM_nCAS(O_sdram_cas_n),
    .SDRAM_CKE(),                 // no board pin; module ties CKE high
    .SDRAM_CLK(O_sdram_clk),
    .init_n(~sdram_rst),
    .clk(clk_sdram),
    // port1 unused (its bank group does not reach the sprite read)
    .port1_req(1'b0), .port1_ack(), .port1_we(1'b0),
    .port1_a(23'd0), .port1_ds(2'b00), .port1_d(16'd0), .port1_q(),
    .cpu1_addr(23'd0), .cpu1_q(),
    .cpu2_addr(23'd0), .cpu2_q(),
    .cpu3_addr(23'd0), .cpu3_q(),
    // port2: sprite download write (shares the sp read's bank 2,3 group)
    .port2_req(p1_req_r), .port2_ack(p1_ack), .port2_we(p1_we_r),
    .port2_a(p1_a_r), .port2_ds(p1_ds_r), .port2_d(p1_d_r), .port2_q(),
    // sprite read to the core: 15-bit word addr -> 32-bit plane word
    // (the post-load sweep, then the one-shot dump, borrow the address bus)
    // EXPERIMENT: core disconnected from the sp bus entirely - ONLY the
    // dump's probe reads may touch the array (core sees frozen sp_q; sprites
    // will render wrong on screen for this build, expected).
    .sp_addr({7'd0, dump_a}),
    .sp_q(sp_q),
    .dbg_refresh(dbg_refresh),
    .dbg_blk0(dbg_blk0), .dbg_blk1(dbg_blk1)
);

wire [15:0] rom_addr;
wire [7:0]  rom_do;
wire [13:0] snd_addr;
wire [7:0]  snd_do;

dpram #(
    .dWidth(8),
    .aWidth(16),
    .INIT_FILE("rom_main.hex")
) rom_cpu_inst (
    .clk_a(clk_sys),
    .we_a(1'b0),
    .addr_a(rom_addr),
    .d_a(8'h00),
    .q_a(rom_do),

    .clk_b(clk_sys),
    .we_b(cpu_rom_we),
    .addr_b(dl_addr[15:0]),
    .d_b(dl_data),
    .q_b() // port B is the ROM download port
);

dpram #(
    .dWidth(8),
    .aWidth(14),
    .INIT_FILE("rom_snd.hex")
) rom_snd_inst (
    .clk_a(clk_sys),
    .we_a(1'b0),
    .addr_a(snd_addr),
    .d_a(8'h00),
    .q_a(snd_do),

    .clk_b(clk_sys),
    .we_b(snd_rom_we),
    .addr_b(dl_addr[13:0]),
    .d_b(dl_data),
    .q_b() // port B is the ROM download port
);

// --- USB HID host (gamepad on USB-A port 1) -----------------------------------
// nand2mario usb_hid_host: low-speed USB, standard HID pads (DInput). The
// board provides the 15k host pulldowns and 5V VBUS. Runs at 12 MHz.
//
// Reset policy - learned from the flash-boot regression: a JTAG load starts
// the design on a board that has been powered for minutes (pad enumerated,
// idle), but an SPI-flash boot starts it right after configuration, while
// the pad's own MCU is still booting. The original 21 us reset ran
// enumeration once into a not-yet-ready pad; the engine then sticks in a
// state it cannot leave on its own - CONFIRMED on hardware: even
// unplug/replug does not revive it, only reset does. So recovery must come
// from out here, and it must not rely on the engine's conerr flag alone
// (the stuck state may never raise it):
//   - hold the host in reset ~350 ms at power-on (slow pads);
//   - whenever NO device is enumerated (typ == 0) or conerr is up,
//     continuously for ~2.8 s, pulse reset and re-enumerate.
// With no pad plugged this is a harmless slow retry loop; late-booting and
// hot-plugged pads get picked up on the next cycle.
reg [22:0] usb_rst_cnt = 23'd0;
reg [24:0] usb_idle_cnt = 25'd0;
wire usb_resetn = usb_rst_cnt[22];        // 2^22 / 12 MHz = 350 ms
wire usb_conerr;
wire [1:0] usb_typ;
always @(posedge clk_usb) begin
    if (!usb_resetn)
        usb_rst_cnt <= usb_rst_cnt + 23'd1;
    if (!usb_resetn || (usb_typ != 2'd0 && !usb_conerr))
        usb_idle_cnt <= 25'd0;
    else begin
        usb_idle_cnt <= usb_idle_cnt + 25'd1;
        if (&usb_idle_cnt) usb_rst_cnt <= 23'd0;  // ~2.8 s dead: re-init
    end
end

wire pad_l, pad_r, pad_u, pad_d;
wire pad_a, pad_b, pad_x, pad_y, pad_sel, pad_sta;

usb_hid_host usb1 (
    .usbclk(clk_usb),
    .usbrst_n(usb_resetn),
    .usb_dm(usb1_dn),
    .usb_dp(usb1_dp),
    .typ(usb_typ),
    .report(),
    .conerr(usb_conerr),
    .key_modifiers(), .key1(), .key2(), .key3(), .key4(),
    .mouse_btn(), .mouse_dx(), .mouse_dy(),
    .game_l(pad_l), .game_r(pad_r), .game_u(pad_u), .game_d(pad_d),
    .game_a(pad_a), .game_b(pad_b), .game_x(pad_x), .game_y(pad_y),
    .game_sel(pad_sel), .game_sta(pad_sta),
    .dbg_hid_report()
);

// Synchronize the (active-high, 12 MHz-domain) pad bits into clk_sys
reg [9:0] pad_sync1 = 0, pad_sync2 = 0;
reg [1:0] usb_typ_s1 = 0, usb_typ_s2 = 0;   // quasi-static, for the beacon
always @(posedge clk_sys) begin
    pad_sync1 <= {pad_l, pad_r, pad_u, pad_d, pad_a, pad_b, pad_x, pad_y, pad_sel, pad_sta};
    pad_sync2 <= pad_sync1;
    usb_typ_s1 <= usb_typ;
    usb_typ_s2 <= usb_typ_s1;
end
wire u_left  = pad_sync2[9], u_right = pad_sync2[8];
wire u_up    = pad_sync2[7], u_down  = pad_sync2[6];
wire u_btn_a = pad_sync2[5], u_btn_b = pad_sync2[4];
wire u_btn_x = pad_sync2[3], u_btn_y = pad_sync2[2];
wire u_sel   = pad_sync2[1], u_sta   = pad_sync2[0];

// Core video signals, declared ahead of everything that references them
wire [2:0] r, g, b;
wire       hblank, vblank;
wire       hs, vs, cs;

// --- Core Controls & Switch Mapping (Tapper) -----------------------------
// MCR-3 Tapper: 2-player, each a 4-way stick + a "pour/serve" button.
// SSIO ports (real board numbering): IP0 = coins/starts/button/tilt/service/
// test (J4 1-8), IP1 = P1 stick (J4 D0-7), IP2 = P2 stick + pour. Pad: dpad
// = P1 stick, A = pour, Start = Start1, Select = Coin1 (board key 2 also
// coins). P2 is tied off for now (single pad); IP3 DIP + the exact P2 bits
// need a MAME cross-check (attract mode does not need them).
wire m_left    = u_left  & ~u_sel & ~osd_active;
wire m_right   = u_right & ~u_sel & ~osd_active;
wire m_up      = u_up    & ~u_sel & ~osd_active;
wire m_down    = u_down  & ~u_sel & ~osd_active;
wire m_pour    = u_btn_a & ~osd_active;
wire m_start1  = u_sta   & ~osd_active;
wire m_start2  = u_btn_x & ~osd_active;
wire m_coin1   = (u_sel & ~osd_active) | key_s2;
wire m_service = 1'b0;

reg [7:0] input_0;
reg [7:0] input_1;
reg [7:0] input_2;
reg [7:0] input_3;
reg [7:0] input_4;

always @(*) begin
    // Verified against MiSTer Arcade-MCR3 (mod_tapper) + Tapper MRA:
    //   IP0 = ~{service,3'b0,start2,start1,1'b0,coin1}
    //   IP1 = IP2 = ~{3'b0,pour,up,down,left,right}   (controls read from BOTH)
    //   IP3 = DIP = 0xFF (MRA default "FF 00" -> sw[0]=FF: upright, demo snd on)
    input_0 = ~{ m_service, 3'b000, m_start2, m_start1, 1'b0, m_coin1 };
    input_1 = ~{ 3'b000, m_pour, m_up, m_down, m_left, m_right };
    input_2 = ~{ 3'b000, m_pour, m_up, m_down, m_left, m_right };
    input_3 = 8'hFF;   // sw[0] per MRA default
    input_4 = 8'hFF;
end

// --- Core Instantiation ---
// (r/g/b/hblank/vblank/hs/vs/cs are declared just before the controls
// section - they are referenced there, and Gowin turns use-before-
// declaration into an implicit 1-bit net with only a warning.)
wire [15:0] audio_l_val, audio_r_val;

wire [9:0] core_hcnt;

mcr3 mcr3_core (
    .clock_40(clk_sys),
    .reset(core_reset),

    // Video outputs (3-bit RGB, same as MCR-2 - no truncation)
    .video_r(r),
    .video_g(g),
    .video_b(b),
    .video_Vblank(vblank),
    .video_hblank(hblank),
    .video_hs(hs),
    .video_vs(vs),
    .video_csync(cs),
    .video_ce(),
    .video_hflip(1'b0),   // upright, no cocktail flip
    .video_vflip(1'b0),
    .hcntout(core_hcnt),

    .tv15Khz_mode(tv15khz),

    .separate_audio(1'b0), // mono mix
    .audio_out_l(audio_l_val),
    .audio_out_r(audio_r_val),

    .input_0(input_0),
    .input_1(input_1),
    .input_2(input_2),
    .input_3(input_3),
    .input_4(input_4),
    .output_4(),           // SSIO output port (lamps/mux) - unused here
    .mcr2p5(1'b0),         // Tapper is 91490 (not Journey/MCR-2.5)

    // CPU + sound ROM (baked in BRAM below); bg is baked inside mcr3.vhd
    .cpu_rom_addr(rom_addr),
    .cpu_rom_do(rom_do),
    .snd_rom_addr(snd_addr),
    .snd_rom_do(snd_do),

    // Sprite ROM: 128 KB in SDRAM (Phase 1). The core drives a 15-bit word
    // address; sdram_gw returns the 32-bit (4-plane) word.
    .sp_addr(core_sp_addr),
    .sp_graphx32_do(sp_q),

    // Download bus (16-bit on MCR-3). Held OFF here: CPU/sound/bg are baked;
    // the SD pack feeds sprites straight to SDRAM (see the sprite loader below).
    .dl_addr(dl_addr[15:0]),
    .dl_wr(1'b0),
    .dl_data(dl_data),
    .dl_nvram_wr(1'b0),
    .dl_din(),
    .dl_nvram(1'b0)
);

// --- Pixel timing shared by the analog and HDMI paths ----------------------
// One strobe per core pixel: hcnt advances at the 20 MHz pixel rate (every
// other clk_sys cycle).
reg [9:0] hcnt_r;
always @(posedge clk_sys) hcnt_r <= core_hcnt;
wire pixel_tick = (hcnt_r != core_hcnt);

// Compensation for the core's RGB-vs-hcnt pipeline lag, used by BOTH video
// paths (analog sync alignment below, HDMI capture window further down).
// LIVE TUNING: hold Select and tap D-pad Right (+1) / Left (-1) while
// watching the left edge - garbage/overlap on the LEFT means increase.
// Reported in the UART beacon as "dXX"; hardcode the winner below.
localparam [4:0] CAP_DELAY_DEFAULT = 5'd13;
reg [4:0] cap_delay = CAP_DELAY_DEFAULT;
reg tune_l_r = 0, tune_r_r = 0;
always @(posedge clk_sys) begin
    tune_l_r <= u_sel & u_left;
    tune_r_r <= u_sel & u_right;
    if (u_sel & u_left  & ~tune_l_r & (cap_delay != 5'd0))  cap_delay <= cap_delay - 1'b1;
    if (u_sel & u_right & ~tune_r_r & (cap_delay != 5'd31)) cap_delay <= cap_delay + 1'b1;
end

// --- On-screen display (game-select menu) -----------------------------------
// Composited onto the core's RGB *here*, before the video path splits, so
// the menu shows up identically on HDMI, 31 kHz VGA and native 15 kHz.
// Select+Start toggles it; Up/Down move, A reloads from the SD pack, B
// exits. The core raster STOPS while a reload holds the core in reset, so
// expect ~1 s of frozen HDMI frame / dropped VGA sync during a switch.
wire [8:0] osd_rgb;
osd #(
    .GAME_DEFAULT(GAME_DEFAULT),
    .NUM_GAMES(4'd1),
    .ROT_MASK(6'b000000),     // Tapper is ROT0 - no OSD text rotation
    .TITLE("    MCR3 GAME SELECT    "),
    .NAME0("   TAPPER               ")
) osd_inst (
    .clk(clk_sys),
    .rst(core_reset_raw),
    .pixel_tick(pixel_tick),
    .hcnt(core_hcnt),
    .hblank(hblank),
    .vblank(vblank),
    .mode15(tv15khz),
    .rgb_in({r, g, b}),
    .rgb_out(osd_rgb),
    .btn_up(u_up), .btn_down(u_down),
    .btn_a(u_btn_a), .btn_b(u_btn_b),
    .btn_sel(u_sel), .btn_sta(u_sta),
    .game_id(game_id),
    .load_slot(game_slot),
    .loader_restart(osd_restart),
    .loader_done(ldr_done),
    .loader_error(ldr_error),
    .loaded_slot(ldr_slot),
    .save_req(osd_save),
    .sd_ready(sd_ready),
    .osd_active(osd_active)
);
// Both video paths consume the OSD-composited pixels from here on.
wire [2:0] vid_r = osd_rgb[8:6];
wire [2:0] vid_g = osd_rgb[5:3];
wire [2:0] vid_b = osd_rgb[2:0];

// --- PmodVGA Analog Output (native core timing, zero buffering) ---
// The core's RGB lags its hcnt-derived sync/blank by a fixed pipeline delay
// (tile fetch -> gfx ROM -> palette -> output regs) - the same lag the HDMI
// capture compensates for with cap_delay. Taking hblank/hs raw here let the
// PREVIOUS line's tail leak into the first ~13 visible pixels (a garbled
// strip down the left edge) while blanking swallowed the last 13 real ones.
// Delay the sync/blank signals by the same amount so they line up with the
// pixels they describe. Shares the live-tunable cap_delay: Select + D-pad
// Right/Left adjusts both paths, value shown in the beacon as "dXX".
reg [31:0] hs_sr, vs_sr, cs_sr, hb_sr, vb_sr;
always @(posedge clk_sys) begin
    if (pixel_tick) begin
        hs_sr <= {hs_sr[30:0], hs};
        vs_sr <= {vs_sr[30:0], vs};
        cs_sr <= {cs_sr[30:0], cs};
        hb_sr <= {hb_sr[30:0], hblank};
        vb_sr <= {vb_sr[30:0], vblank};
    end
end
wire [4:0] vga_tap = (cap_delay == 5'd0) ? 5'd0 : cap_delay - 5'd1;
wire hs_d     = (cap_delay == 5'd0) ? hs     : hs_sr[vga_tap];
wire vs_d     = (cap_delay == 5'd0) ? vs     : vs_sr[vga_tap];
wire cs_d     = (cap_delay == 5'd0) ? cs     : cs_sr[vga_tap];
wire hblank_d = (cap_delay == 5'd0) ? hblank : hb_sr[vga_tap];
wire vblank_d = (cap_delay == 5'd0) ? vblank : vb_sr[vga_tap];

// 3:3:3 -> 4:4:4 by MSB replication so full intensity maps to full scale.
// Blank the DAC outside active video so the monitor sees black porches.
wire cab_blank = hblank_d | vblank_d;
assign vga_r = cab_blank ? 4'h0 : {vid_r, vid_r[2]};
assign vga_g = cab_blank ? 4'h0 : {vid_g, vid_g[2]};
assign vga_b = cab_blank ? 4'h0 : {vid_b, vid_b[2]};

// Sync format. 31 kHz always uses separate negative H/V (standard RGBHV).
//
// 15 kHz also defaults to SEPARATE H and V sync, for two reasons: it is what
// a real MCR cabinet expects (the Video connector has discrete H-Sync on
// pin 8 and V-Sync on pin 9), and modern 15 kHz-capable displays detect it
// reliably. Composite sync was the old default and cost a long debug session
// - one LCD silently dropped its entire green channel, apparently deciding a
// csync source must carry sync-on-green and clamping that input. Note such
// displays latch their format detection, so a wrong guess persists until
// sync is disturbed; changing format while running may not re-trigger it.
//
// Strap J10-39 to GND for composite sync on HS instead (RGBS - what an
// OSSC/RetroTink or an SOG-wired monitor may prefer).
// Strap J10-40 to GND to hold VS inactive (pure single-sync RGBS).
wire want_csync = ~map_rows_n;   // J10-39 to GND
wire vsync_off  = ~map_sock_n;   // J10-40 to GND

assign vga_hs = (tv15khz && want_csync) ? cs_d : hs_d;
assign vga_vs = vsync_off ? 1'b1 : vs_d;

// --- PmodVGA plugged directly into the PMOD sockets --------------------------
// Sipeed socket columns (anchored at the power end, which mates with the
// Pmod's VCC/GND columns): [3V3][GND][IO6/7][IO4/5][IO2/3][IO0/1].
// Digilent columns from the same end: [VCC][GND][4/10][3/9][2/8][1/7].
// => forced column pairing: Pmod pins {1,2,3,4} land on even-or-odd IOs
// {0,2,4,6} and pins {7,8,9,10} on the other row - which row is which, and
// which socket meets PmodVGA J1 (R/B) vs J2 (G/sync), depends on physical
// orientation we can't see in the schematic. Both unknowns are runtime
// straps: try the 4 combinations, exactly one shows a stable picture.
wire row_swap  = ~map_rows_n;   // strap to GND to swap rows
wire sock_swap = ~map_sock_n;   // strap to GND to swap sockets

// Socket carrying PmodVGA J1 (R + B ladders)
wire [7:0] j1_rows_a = {vga_b[3], vga_r[3], vga_b[2], vga_r[2],
                        vga_b[1], vga_r[1], vga_b[0], vga_r[0]}; // IO7..IO0
wire [7:0] j1_rows_b = {vga_r[3], vga_b[3], vga_r[2], vga_b[2],
                        vga_r[1], vga_b[1], vga_r[0], vga_b[0]};
wire [7:0] j1_bus = row_swap ? j1_rows_b : j1_rows_a;

// Socket carrying PmodVGA J2 (G ladder + HS/VS; Pmod pins 9/10 are NC)
wire [7:0] j2_rows_a = {1'b0, vga_g[3], 1'b0, vga_g[2],
                        vga_vs, vga_g[1], vga_hs, vga_g[0]};     // IO7..IO0
wire [7:0] j2_rows_b = {vga_g[3], 1'b0, vga_g[2], 1'b0,
                        vga_g[1], vga_vs, vga_g[0], vga_hs};
wire [7:0] j2_bus = row_swap ? j2_rows_b : j2_rows_a;

assign pmod0_io = sock_swap ? j2_bus : j1_bus;
assign pmod1_io = sock_swap ? j1_bus : j2_bus;

// --- HDMI Output: DDR3 framebuffer -> 1280x720@60 (nand2mario/gbatang) ------
// The core streams its native 512x480 image into a DDR3-backed framebuffer,
// which upscales to 720p (game shown 960 wide for 4:3) and drives HDMI with
// audio. This fully decouples core and display timing: no line buffer, no
// genlock, no shimmer. In 15 kHz mode the capture height drops to 240 lines
// per field and the upscaler adapts (integer 3x).

// The core's RGB output lags its hcnt by a fixed pipeline delay (tile fetch ->
// gfx ROM -> palette -> output regs); shift the capture window back by
// cap_delay so each line's pixels land at the right offsets.
// LIVE TUNING: hold Select and tap D-pad Right (+1) / Left (-1) while
// watching the left edge - garbage/overlap on the LEFT means increase.
// The current value is reported in the UART beacon as "dXX" (hex); once the
// sweet spot is found, hardcode it as the reset value below.
// (The D-pad is masked from the game while Select is held; note Select
// itself still inserts a coin - harmless during tuning.)


wire cap_active = !vblank && (core_hcnt >= {5'b0, cap_delay}) && (core_hcnt < {5'b0, cap_delay} + 10'd512);
wire fb_we = pixel_tick && cap_active;
// RGB444: replicate each 3-bit channel's MSB into bit 0 (as the VGA DAC does)
wire [11:0] fb_data = {vid_r, vid_r[2], vid_g, vid_g[2], vid_b, vid_b[2]};

// Single-cycle frame pulse after the last active line (vblank rising edge)
reg fb_vbl_r = 1'b1;
always @(posedge clk_sys) fb_vbl_r <= vblank;
wire fb_vsync = vblank & ~fb_vbl_r;

// DDR3/HDMI bring-up debug on spare J10 pins (probe vs GND with a DMM):
//   debug_o[0] J10-21: init_calib_complete - steady 3.3V = DDR3 trained
//   debug_o[1] J10-22: ~1.1Hz heartbeat from clk_x1 (74.25MHz pixel clock)
//   debug_o[2] J10-23: ~0.8Hz heartbeat from the 27MHz reference
//   debug_o[3] J10-24: ddr_rst - should sit LOW once the DDR PLL settles
wire fb_clk_x1, fb_ddr_rst, fb_calib;
wire fb_hclk;             // HDMI pixel clock (74.25 MHz expected)
// NOTE: do not hang a counter on hclk5 (371 MHz). It is unconstrained in the
// SDC, so the tool cannot see the speed, and the added logic disturbed the
// DDR3 interface enough to stop it calibrating (beacon showed c0). hclk5 was
// measured this way once and confirmed at 5x hclk; that is enough.
reg [24:0] hb_h = 0;
always @(posedge fb_hclk) hb_h <= hb_h + 1'b1;
reg [25:0] hb_x1 = 0;
reg [24:0] hb_27 = 0;
always @(posedge fb_clk_x1) hb_x1 <= hb_x1 + 1'b1;
always @(posedge clk27)     hb_27 <= hb_27 + 1'b1;
assign debug_o = {fb_ddr_rst, hb_27[24], hb_x1[25], fb_calib};

// Same vitals over USB-C serial (BL616 bridges the U15 UART), for debugging
// with the case closed: frozen x____ across lines = pixel clock dead,
// frozen q__ = 27MHz chain dead, c0/r1 = DDR3 never trained.
// DIAGNOSTIC beacon x/q mux: until a sweep has completed, x/q show the
// sprite write counter as before (x ~= 0x0200 per full 128 KB load). Once
// chk_done, x rotates (~0.8 s per phase) through the sweep counters, with q
// tagging which one is showing:
//   qE0: x = words read back as all-FF        (expect ~0)
//   qE1: x = words with both DQML lanes FF    (~0x7Fxx = low byte lane dead)
//   qE2: x = words with both DQMH lanes FF    (~0x7Fxx = high byte lane dead)
//   qE3: x = write counter [23:8] again
reg [26:0] diag_cnt = 0;
always @(posedge clk_sys) diag_cnt <= diag_cnt + 1'b1;
wire [1:0]  diag_ph = diag_cnt[26:25];
// E1 repurposed: live AUTO_REFRESH issue counter (sweep is disabled).
// A DIFFERENT xE1 value on every beacon line = refresh commands are being
// issued (~133k/s, wraps ~2x/s); frozen x0000 qE1 = the branch never fires.
wire [15:0] diag_x = !chk_done_s     ? spw_count_s[23:8] :
                     diag_ph == 2'd0 ? dbg_blk0_s :
                     diag_ph == 2'd1 ? rw_lat_s :              // E1 = refreshes per 104.9ms window
                     diag_ph == 2'd2 ? dbg_blk1_s : spw_count_s[23:8];
wire [7:0]  diag_q = !chk_done_s     ? spw_count_s[7:0] :
                     diag_ph == 2'd0 ? 8'hE0 :
                     diag_ph == 2'd1 ? 8'hE1 :
                     diag_ph == 2'd2 ? 8'hE2 : 8'hE3;

// DIAGNOSTIC: the one-shot SDRAM dump borrows the UART pin while it runs
wire beacon_txd;
assign uart_tx = dump_active ? dump_txd : beacon_txd;

uart_beacon #(.CLK_HZ(40_000_000), .BAUD(115200)) beacon (
    .clk(clk_sys),
    .calib(fb_calib),
    .ddr_rst(fb_ddr_rst),
    // L bit7 = spq_nonff: sp_q was seen != all-ones at least once (=1 means the
    //   sprite read returned real data; =0 means it is stuck all-ones).
    .cnt_x(diag_x),
    .cnt_q(diag_q),
    .aux({game_id, cap_delay}),   // dXX: high 3 bits = running game_id
    // L bit7 = spq_nonff (sprite read saw non-FF data); rest = SD/loader flags.
    .aux2({spq_nonff_s, hb_h[23], usb_typ_s2, sd_ready, sd_err, ldr_done, ldr_error}),
    .txd(beacon_txd)
);

ddr3_framebuffer #(
    .WIDTH(512),
    .HEIGHT(480),
    .COLOR_BITS(12),
    .PREFETCH_DELAY(44),
    .DVI_MODE(0)          // full HDMI, as NESTang uses
) fb_inst (
    .hclk_dbg(fb_hclk),
    .clk_27(clk27),
    .pll_lock_27(1'b1),
    .clk_g(clk50_pll),        // PLL-buffered 50 MHz (global clock net)
    .clk_out(fb_clk_x1),
    // Reset from the power-on counter ONLY - never from rom_ready. Video must
    // come up independently of ROM loading, otherwise a stalled/slow SD load
    // takes HDMI sync down with it and there is nothing to diagnose from.
    .rst_n(~core_reset_raw),
    .ddr_rst(fb_ddr_rst),
    .init_calib_complete(fb_calib),
    .ddr_prefetch_delay(6'd44),

    // Framebuffer write interface (core pixel stream)
    .clk(clk_sys),
    .fb_width(11'd512),
    .fb_height(tv15khz ? 10'd240 : 10'd480),
    .disp_width(11'd960),     // 4:3 within the 720p canvas
    .fb_vsync(fb_vsync),
    .fb_we(fb_we),
    .fb_data(fb_data),

    // HDMI audio (offset-binary core mix -> signed PCM)
    .sound_left(audio_l_val ^ 16'h8000),
    .sound_right(audio_r_val ^ 16'h8000),

    // DDR3 (on-SOM 4Gb x16)
    .ddr_addr(ddr_addr),
    .ddr_bank(ddr_bank),
    .ddr_cs(ddr_cs),
    .ddr_ras(ddr_ras),
    .ddr_cas(ddr_cas),
    .ddr_we(ddr_we),
    .ddr_ck(ddr_ck),
    .ddr_ck_n(ddr_ck_n),
    .ddr_cke(ddr_cke),
    .ddr_odt(ddr_odt),
    .ddr_reset_n(ddr_reset_n),
    .ddr_dm(ddr_dm),
    .ddr_dq(ddr_dq),
    .ddr_dqs(ddr_dqs),
    .ddr_dqs_n(ddr_dqs_n),

    // HDMI out
    .tmds_clk_n(tmds_clk_n),
    .tmds_clk_p(tmds_clk_p),
    .tmds_d_n(tmds_d_n),
    .tmds_d_p(tmds_d_p)
);

// --- PWM Audio Modulators ---
ds_dac dac_l (
    .clk(clk_sys),
    .resetn(~core_reset),
    .din(audio_l_val),
    .dout(audio_l)
);

ds_dac dac_r (
    .clk(clk_sys),
    .resetn(~core_reset),
    .din(audio_r_val),
    .dout(audio_r)
);

endmodule
