// Timing constraints for MCR2 on Tang Primer 25K
// Define primary input 50MHz clock on pin sys_clk (period = 20ns)
create_clock -name sys_clk -period 20 -waveform {0 10} [get_ports {sys_clk}]

// Gowin's timing analysis engine automatically derives the rest of the clocks
// generated by the PLLA and CLKDIV primitives.
