// game_config.vh is generated by `python3 tools/merge_roms.py <game>` and
// must match the ROM hex files: it defines GAME_TRON / GAME_DOMINO /
// GAME_SHOLLOW to select the per-game input & DIP mapping below.
`include "game_config.vh"

// Tang Console 60K Top-Level Wrapper for MCR2 Arcade Core
// Video: DDR3-backed framebuffer (nand2mario/gbatang) upscaling the core's
// native 512x480 to 1280x720 HDMI with audio, plus concurrent analog VGA
// (PmodVGA / RGB DAC) at native 31/15 kHz timing. ROMs live in BSRAM;
// gamepad on USB port 1.
module mcr2_console60k_top (
    input        sys_clk,       // 50 MHz on-board oscillator (pin V22)
    input        s1,            // User key AA13 - ACTIVE LOW on console (pull-up)
    input        reset2,        // User key AB13 - ACTIVE LOW on console (pull-up)

    // DVI/HDMI output.
    // hpd_en drives the dock's HDMI enable. Sipeed's own NEO_DOCK example
    // drives this pin at DRIVE=12; nand2mario's cores leave it unassigned
    // (tri-stated with a weak internal pull-up), which is what we did too.
    // If the net has an external pull-down, that weak pull-up loses and the
    // dock's HDMI stays disabled - and because JTAG reconfiguration does not
    // power-cycle the board, whether a previous core left the line high can
    // decide if a picture appears. Drive it explicitly.
    output       hpd_en,
    output       tmds_clk_p,
    output       tmds_clk_n,
    output [2:0] tmds_d_p,
    output [2:0] tmds_d_n,

    // On-SOM DDR3 (framebuffer backing store; pins from gbatang console60k)
    output [14:0] ddr_addr,
    output [2:0]  ddr_bank,
    output        ddr_cs,
    output        ddr_ras,
    output        ddr_cas,
    output        ddr_we,
    output        ddr_ck,
    output        ddr_ck_n,
    output        ddr_cke,
    output        ddr_odt,
    output        ddr_reset_n,
    output [1:0]  ddr_dm,
    inout  [15:0] ddr_dq,
    inout  [1:0]  ddr_dqs,
    inout  [1:0]  ddr_dqs_n,

    // PMOD sockets, repurposed to host the Digilent PmodVGA directly.
    // (Desk buttons retired - inputs come from the USB pad and board keys.)
    // Sipeed socket IO order differs from Digilent pin order; the physical
    // row/socket orientation is resolved at runtime by the two map_* straps.
    output [7:0] pmod0_io,
    output [7:0] pmod1_io,
    input        map_rows_n,     // J10-39 strap: open/GND = try both
    input        map_sock_n,     // J10-40 strap: open/GND = try both

    // Digilent PmodVGA (4:4:4 + HS/VS) wired to J10 header - see CST for the
    // jumper recipe. Analog output has no line buffer -> no shimmer/tearing.
    output [3:0] vga_r,
    output [3:0] vga_g,
    output [3:0] vga_b,
    output       vga_hs,
    output       vga_vs,

    // 15/31 kHz select strap on J10 (internal pull-up):
    // open = 31 kHz progressive (VGA monitor), jumper to GND = 15 kHz
    // native arcade timing (CRT / OSSC / RetroTink; VGA LCDs will not sync)
    input        mode15_n,

    // USB-A port 1 (left) - USB HID host (15k pulldowns are on the board)
    inout        usb1_dp,
    inout        usb1_dn,

    // MicroSD card (SPI mode) - optional ROM source, see rom_loader.sv
    output       sd_clk,
    output       sd_cmd,      // MOSI
    input        sd_dat0,     // MISO
    output       sd_dat3,     // CS

    // DDR3/HDMI bring-up debug (J10 pins 21-24; see comment at the logic)
    output [3:0] debug_o,

    // Status beacon on the FPGA->BL616 UART (shows up as USB-C serial,
    // 115200 8N1): one "FB c_ r_ x____ q__" line every ~0.5s
    output       uart_tx,

    // PWM Audio output
    output       audio_l,
    output       audio_r
);

assign hpd_en = 1'b1;   // enable the dock's HDMI path

// --- Clock Generation ---
wire clk_sys;  // 40 MHz  (Core system clock, generates 20 MHz pixel enable)
wire clk_p5;   // 125 MHz (HDMI 5x pixel clock)
wire pll_locked;

wire clk50_pll;  // PLL-buffered 50 MHz for the DDR3 controller/mDRP (clk_g).
                 // Feeding the raw pad clock there put a derived clock on
                 // generic routing (PR1014) and the DDR3 IP never came up.
gowin_pll_mcr2 pll_inst (
    .clkin(sys_clk),
    .clk_sys(clk_sys),
    .clk_p5(clk_p5),
    .clk_50(clk50_pll),
    .lock(pll_locked)
);

// 27 MHz reference for the DDR3 framebuffer's internal PLLs (720p + DDR3)
wire clk27;
pll_27 pll27_inst (
    .clkin(sys_clk),
    .clkout0(clk27)
);

// Second PLLA: 50 MHz -> exactly 12 MHz for the USB HID host
// (VCO = 50*18 = 900 MHz, ODIV0 = 75; config from nand2mario's usb_hid_host)
wire clk_usb;
gowin_pll_usb pll_usb_inst (
    .clkin(sys_clk),
    .clkout(clk_usb)
);

// --- Reset Generation ---
// Unlike the Primer 25K (buttons active high w/ pulldown), the Tang Console's
// user keys are active LOW with pull-ups. Invert once here; the rest of the
// design keys off the active-high key_s1/key_s2 exactly like the 25K top.
wire key_s1 = ~s1;
wire key_s2 = ~reset2;

// 15 kHz strap, synchronized into the core clock domain (active low pin).
// Live toggling works; if the picture is disturbed after moving the jumper,
// press S1 (reset) once.
reg mode15_s1 = 0, mode15_s2 = 0;
always @(posedge clk_sys) begin
    mode15_s1 <= ~mode15_n;
    mode15_s2 <= mode15_s1;
end
wire tv15khz = mode15_s2;

// (Video note: the DDR3 framebuffer captures whatever timing the core emits,
// so HDMI stays alive in 15 kHz mode too - capture height drops to 240
// lines per field and the upscaler adapts.)

reg [7:0] reset_cnt = 255;
wire      rom_ready;                          // ROM image settled
wire core_reset_raw = (reset_cnt != 0);       // resets the SD loader itself
wire core_reset     = core_reset_raw || !rom_ready;   // resets the game core

// Which slot of the SD pack to load. Fixed for now; this is what the
// SW1-3..5 game-select DIPs will drive once the 74HC165 chain exists
// (docs/universal_mcr_shield_spec.md section 7).
wire [3:0] game_slot = 4'd0;

always @(posedge clk_sys) begin
    if (key_s1 || !pll_locked) begin
        reset_cnt <= 255;
    end else if (reset_cnt != 0) begin
        reset_cnt <= reset_cnt - 8'd1;
    end
end

// --- ROM source ---------------------------------------------------------
// The INIT_FILE contents are the power-on default (whatever game
// `merge_roms.py` last generated - Tron by default), so the board always
// boots something even with no SD card. When a card holding a valid pack is
// present, rom_loader overwrites these memories before the core leaves
// reset and the DIP-selected game runs instead.
wire        sd_ready, sd_err, sd_rd_start, sd_rd_done, sd_dv;
wire [7:0]  sd_dout;
wire [31:0] sd_sector;
wire [16:0] dl_addr;
wire [7:0]  dl_data;
wire        dl_wr;
wire        ldr_done, ldr_error;

// Core runs once the loader has finished, or as soon as it gives up on a
// missing/unreadable card (then the baked-in ROMs stand).
assign rom_ready = ldr_done | ldr_error;

sd_reader #(.CLK_HZ(40_000_000)) sd (
    .clk(clk_sys), .rst(core_reset_raw),
    .ready(sd_ready), .err(sd_err),
    .rd_start(sd_rd_start), .rd_sector(sd_sector),
    .dout(sd_dout), .dout_valid(sd_dv), .rd_done(sd_rd_done),
    .sclk(sd_clk), .mosi(sd_cmd), .miso(sd_dat0), .cs_n(sd_dat3)
);

rom_loader #(.PACK_BASE(32'd2048), .SLOT_SECTORS(256)) loader (
    .clk(clk_sys), .rst(core_reset_raw),
    .slot(game_slot),
    .sd_ready(sd_ready), .sd_err(sd_err),
    .sd_rd_start(sd_rd_start), .sd_sector(sd_sector),
    .sd_dout(sd_dout), .sd_dout_valid(sd_dv), .sd_rd_done(sd_rd_done),
    .dl_addr(dl_addr), .dl_data(dl_data), .dl_wr(dl_wr),
    .done(ldr_done), .error(ldr_error)
);

// Download decode for the two ROMs that live here (the gfx ROMs decode
// inside mcr2.vhd): CPU 0x00000-0x0FFFF, sound 0x10000-0x13FFF.
wire cpu_rom_we = dl_wr && !dl_addr[16];
wire snd_rom_we = dl_wr && (dl_addr[16:14] == 3'b100);

wire [15:0] rom_addr;
wire [7:0]  rom_do;
wire [13:0] snd_addr;
wire [7:0]  snd_do;

dpram #(
    .dWidth(8),
    .aWidth(16),
    .INIT_FILE("rom_main.hex")
) rom_cpu_inst (
    .clk_a(clk_sys),
    .we_a(1'b0),
    .addr_a(rom_addr),
    .d_a(8'h00),
    .q_a(rom_do),

    .clk_b(clk_sys),
    .we_b(cpu_rom_we),
    .addr_b(dl_addr[15:0]),
    .d_b(dl_data),
    .q_b() // port B is the ROM download port
);

dpram #(
    .dWidth(8),
    .aWidth(14),
    .INIT_FILE("rom_snd.hex")
) rom_snd_inst (
    .clk_a(clk_sys),
    .we_a(1'b0),
    .addr_a(snd_addr),
    .d_a(8'h00),
    .q_a(snd_do),

    .clk_b(clk_sys),
    .we_b(snd_rom_we),
    .addr_b(dl_addr[13:0]),
    .d_b(dl_data),
    .q_b() // port B is the ROM download port
);

// --- USB HID host (gamepad on USB-A port 1) -----------------------------------
// nand2mario usb_hid_host: low-speed USB, standard HID pads (DInput). The
// board provides the 15k host pulldowns and 5V VBUS. Runs at 12 MHz.
reg [7:0] usb_rst_cnt = 8'hFF;
wire usb_resetn = (usb_rst_cnt == 8'd0);
always @(posedge clk_usb) begin
    if (usb_rst_cnt != 0) usb_rst_cnt <= usb_rst_cnt - 8'd1;
end

wire pad_l, pad_r, pad_u, pad_d;
wire pad_a, pad_b, pad_x, pad_y, pad_sel, pad_sta;

usb_hid_host usb1 (
    .usbclk(clk_usb),
    .usbrst_n(usb_resetn),
    .usb_dm(usb1_dn),
    .usb_dp(usb1_dp),
    .typ(),
    .report(),
    .conerr(),
    .key_modifiers(), .key1(), .key2(), .key3(), .key4(),
    .mouse_btn(), .mouse_dx(), .mouse_dy(),
    .game_l(pad_l), .game_r(pad_r), .game_u(pad_u), .game_d(pad_d),
    .game_a(pad_a), .game_b(pad_b), .game_x(pad_x), .game_y(pad_y),
    .game_sel(pad_sel), .game_sta(pad_sta),
    .dbg_hid_report()
);

// Synchronize the (active-high, 12 MHz-domain) pad bits into clk_sys
reg [9:0] pad_sync1 = 0, pad_sync2 = 0;
always @(posedge clk_sys) begin
    pad_sync1 <= {pad_l, pad_r, pad_u, pad_d, pad_a, pad_b, pad_x, pad_y, pad_sel, pad_sta};
    pad_sync2 <= pad_sync1;
end
wire u_left  = pad_sync2[9], u_right = pad_sync2[8];
wire u_up    = pad_sync2[7], u_down  = pad_sync2[6];
wire u_btn_a = pad_sync2[5], u_btn_b = pad_sync2[4];
wire u_btn_x = pad_sync2[3], u_btn_y = pad_sync2[2];
wire u_sel   = pad_sync2[1], u_sta   = pad_sync2[0];

// Core video signals, declared ahead of everything that references them
wire [2:0] r, g, b;
wire       hblank, vblank;
wire       hs, vs, cs;

// --- Core Controls & Switch Mapping (per game, verified vs MAME mcr.cpp) -----
// All inputs come from the USB pad (PMOD sockets carry the PmodVGA):
// common decode: dpad = joystick, A = Button 1, Start = Start1,
// Select = Coin1. B/X/Y are game-specific. Board key 2 also pulses Coin 1.
// D-pad is masked while Select is held (Select+dpad = capture-delay tuning).
wire m_left    = u_left  & ~u_sel;
wire m_right   = u_right & ~u_sel;
wire m_up      = u_up    & ~u_sel;
wire m_down    = u_down  & ~u_sel;
wire m_start1  = u_sta;
wire m_coin1   = u_sel | key_s2;
wire m_service = 1'b0;

reg [7:0] input_0;
reg [7:0] input_1;
reg [7:0] input_2;
reg [7:0] input_3;
reg [7:0] input_4;

`ifdef GAME_TRON
// TRON: IP0 = standard MCR2 (trigger on bit 4), IP1 = 8-bit aim dial
// (absolute spinner value, NOT active-low switches), IP2 = P1 8-way
// joystick, IP3 DIPs = 0x80 (upright, coin meters 2, continues allowed,
// cocktail-trigger input idle high), IP4 = cocktail dial (unused).
// Pad: dpad = move, A/B = trigger, X/Y = rotate aim. If the aim rotates
// opposite to expectation (MAME marks this dial PORT_REVERSE), swap the
// minus/plus hookup below.
wire m_fire   = u_btn_a | u_btn_b;
wire m_start2 = 1'b0;   // X/Y are the spinner on this game
wire m_coin2  = 1'b0;

wire [7:0] spin_out;
spinner #(.INC_NORMAL(20), .INC_FAST(40), .INC_SPINNER(20)) aim_dial (
    .clk(clk_sys),
    .reset(core_reset),
    .minus(u_btn_x),
    .plus(u_btn_y),
    .fast(1'b0),
    .strobe(vblank),   // steps once per frame (module edge-detects)
    .spin_in(9'd0),    // reserved: USB mouse as a true spinner
    .spin_out(spin_out)
);

always @(*) begin
    input_0 = ~{ 1'b0, m_service, 1'b0, m_fire, m_start2, m_start1, m_coin2, m_coin1 };
    input_1 = spin_out;
    input_2 = ~{ 4'b0000, m_down, m_up, m_right, m_left };
    input_3 = 8'h80;
    input_4 = 8'h00;
end

`elsif GAME_WACKO
// WACKO: trackball game. IP1 = trackball X, IP2 = trackball Y (both are
// free-running 8-bit counters, exactly what spinner.sv produces), IP4 =
// 4-way "left" joystick that aims. The SSIO input mux (output port 4 bit 0)
// only swaps in the *cocktail* player's trackball, so upright play needs no
// mux support. Pad: dpad = trackball, X/Y+A/B = aim stick.
wire m_start2 = 1'b0;   // no spare buttons: A/B/X/Y are the aim joystick
wire m_coin2  = 1'b0;

wire [7:0] tb_x, tb_y;
spinner #(.INC_NORMAL(12), .INC_FAST(24), .INC_SPINNER(12)) trackball_x (
    .clk(clk_sys), .reset(core_reset),
    .minus(m_left), .plus(m_right), .fast(1'b0), .strobe(vblank),
    .spin_in(9'd0), .spin_out(tb_x)
);
spinner #(.INC_NORMAL(12), .INC_FAST(24), .INC_SPINNER(12)) trackball_y (
    .clk(clk_sys), .reset(core_reset),
    .minus(m_up), .plus(m_down), .fast(1'b0), .strobe(vblank),
    .spin_in(9'd0), .spin_out(tb_y)
);

always @(*) begin
    input_0 = ~{ 1'b0, m_service, 1'b0, 1'b0, m_start2, m_start1, m_coin2, m_coin1 };
    input_1 = tb_x;
    input_2 = tb_y;
    input_3 = 8'hFF;
    // IP4 aim joystick, 4-way active low: bit3 up, bit2 down, bit1 left, bit0 right
    input_4 = ~{ 4'b0000, u_btn_a, u_btn_b, u_btn_x, u_btn_y };
end

`elsif GAME_KROOZR
// KOZMIK KROOZR: IP1 packs the rotating-cockpit spinner oddly - the SSIO
// custom read returns ((dial & 0x80) >> 1) | ((dial & 0x70) >> 4), i.e.
// bit 6 = dial[7] and bits 2:0 = dial[6:4], both ACTIVE HIGH; bit 7 is
// Button 2 (active low) and bits 5:3 are cockpit sensors. IP2/IP4 are an
// analogue stick (0x30..0x98, centre 0x64) synthesised here from the d-pad.
wire m_start2 = u_btn_x;
wire m_coin2  = u_btn_y;

wire [7:0] dial;
spinner #(.INC_NORMAL(16), .INC_FAST(32), .INC_SPINNER(16)) cockpit_dial (
    .clk(clk_sys), .reset(core_reset),
    .minus(u_btn_x), .plus(u_btn_y), .fast(1'b0), .strobe(vblank),
    .spin_in(9'd0), .spin_out(dial)
);

// analogue stick: ramp toward the limit while held, recentre on release
reg vbl_r = 1'b1;
wire vbl_edge = vblank & ~vbl_r;
always @(posedge clk_sys) vbl_r <= vblank;

reg [7:0] stick_x = 8'h64, stick_y = 8'h64;
always @(posedge clk_sys) begin
    if (vbl_edge) begin
        if      (m_left  && stick_x > 8'h30) stick_x <= stick_x - 8'd4;
        else if (m_right && stick_x < 8'h98) stick_x <= stick_x + 8'd4;
        else if (!m_left && !m_right)        stick_x <= 8'h64;

        if      (m_up    && stick_y > 8'h30) stick_y <= stick_y - 8'd4;
        else if (m_down  && stick_y < 8'h98) stick_y <= stick_y + 8'd4;
        else if (!m_up && !m_down)           stick_y <= 8'h64;
    end
end

always @(*) begin
    input_0 = ~{ 1'b0, m_service, 1'b0, u_btn_a, m_start2, m_start1, m_coin2, m_coin1 };
    // bit 7 Button 2 (active low), bits 5:3 sensors (idle low), spinner bits high-active
    input_1 = { ~u_btn_b, dial[7], 3'b000, dial[6:4] };
    input_2 = stick_x;
    input_3 = 8'hFF;
    input_4 = stick_y;
end

`elsif GAME_TWOTIGER
// TWO TIGERS (Tron-conversion set): twin spinners. IP1 = player 1 dial,
// IP4 = player 2 dial, IP2 low nibble = the four fire buttons, and IP0
// bit 4 is "Dogfight Start". Pad: X/Y spin, A/B fire.
wire m_start2 = 1'b0;
wire m_coin2  = 1'b0;

wire [7:0] dial1;
spinner #(.INC_NORMAL(20), .INC_FAST(40), .INC_SPINNER(20)) tt_dial (
    .clk(clk_sys), .reset(core_reset),
    .minus(u_btn_x), .plus(u_btn_y), .fast(1'b0), .strobe(vblank),
    .spin_in(9'd0), .spin_out(dial1)
);

always @(*) begin
    // bit 4 = Dogfight Start (start 3)
    input_0 = ~{ 1'b0, m_service, 1'b0, u_sel & u_sta, 1'b0, m_start1, m_coin2, m_coin1 };
    input_1 = dial1;
    input_2 = ~{ 4'b0000, 2'b00, u_btn_b, u_btn_a };
    input_3 = 8'hFF;
    input_4 = 8'h00;   // player 2 dial
end

`elsif GAME_SHOLLOW
// SATAN'S HOLLOW: IP0 = standard (no button bit), IP1 = {..., fire,
// shield, right, left}. Pad: A = fire, B = shield, X = Start2, Y = Coin2.
wire m_start2 = u_btn_x;
wire m_coin2  = u_btn_y;

always @(*) begin
    input_0 = ~{ 2'b00, 1'b0, 1'b0, m_start2, m_start1, m_coin2, m_coin1 };
    input_1 = ~{ 4'b0000, u_btn_a, u_btn_b, m_right, m_left };
    input_2 = 8'hFF;
    input_3 = 8'hFF;
    input_4 = 8'hFF;
end

`else
// DOMINO MAN (default): IP0 = standard (Place/Strike on bit 4), IP1 =
// 4-way joystick. IP3 DIPs = 0x3E: Music On, light skin, bits2-5 unused
// (idle high), Upright (bit6 LOW - 0xFF would select cocktail!), two coin
// meters. Pad: A/B = Place/Strike, X = Start2, Y = Coin2.
wire m_fire   = u_btn_a | u_btn_b;
wire m_start2 = u_btn_x;
wire m_coin2  = u_btn_y;

always @(*) begin
    input_0 = ~{ 1'b0, m_service, 1'b0, m_fire, m_start2, m_start1, m_coin2, m_coin1 };
    input_1 = ~{ 4'b0000, m_down, m_up, m_right, m_left };
    input_2 = 8'hFF;
    input_3 = 8'h3E;
    input_4 = 8'hFF;
end
`endif

// --- Core Instantiation ---
// (r/g/b/hblank/vblank/hs/vs/cs are declared just before the controls
// section - they are referenced there, and Gowin turns use-before-
// declaration into an implicit 1-bit net with only a warning.)
wire [15:0] audio_l_val, audio_r_val;

wire [9:0] core_hcnt;
wire [9:0] core_vcnt;

mcr2 mcr2_core (
    .clock_40(clk_sys),
    .reset(core_reset),

    // Video outputs
    .video_r(r),
    .video_g(g),
    .video_b(b),
    .video_vblank(vblank),
    .video_hblank(hblank),
    .video_hs(hs),
    .video_vs(vs),
    .video_csync(cs),
    .hcnt_out(core_hcnt),
    .vcnt_out(core_vcnt),

    // 0 = 31kHz scan-doubled progressive (HDMI + VGA monitor),
    // 1 = native 15kHz arcade timing (CRT/scan converter via PmodVGA).
    // Selected by the mode15_n strap on J10.
    .tv15Khz_mode(tv15khz),

    .separate_audio(1'b0), // mono mix
    .audio_out_l(audio_l_val),
    .audio_out_r(audio_r_val),

    .input_0(input_0),
    .input_1(input_1),
    .input_2(input_2),
    .input_3(input_3),
    .input_4(input_4),

    // CPU ROM interface
    .cpu_rom_addr(rom_addr),
    .cpu_rom_do(rom_do),
    .snd_rom_addr(snd_addr),
    .snd_rom_do(snd_do),

    // Disable HPS download interface
    .dl_addr(dl_addr),
    .dl_wr(dl_wr),
    .dl_data(dl_data),
    .dl_nvram_wr(1'b0),
    .dl_din(),
    .dl_nvram(1'b0)
);

// --- Pixel timing shared by the analog and HDMI paths ----------------------
// One strobe per core pixel: hcnt advances at the 20 MHz pixel rate (every
// other clk_sys cycle).
reg [9:0] hcnt_r;
always @(posedge clk_sys) hcnt_r <= core_hcnt;
wire pixel_tick = (hcnt_r != core_hcnt);

// Compensation for the core's RGB-vs-hcnt pipeline lag, used by BOTH video
// paths (analog sync alignment below, HDMI capture window further down).
// LIVE TUNING: hold Select and tap D-pad Right (+1) / Left (-1) while
// watching the left edge - garbage/overlap on the LEFT means increase.
// Reported in the UART beacon as "dXX"; hardcode the winner below.
localparam [4:0] CAP_DELAY_DEFAULT = 5'd13;
reg [4:0] cap_delay = CAP_DELAY_DEFAULT;
reg tune_l_r = 0, tune_r_r = 0;
always @(posedge clk_sys) begin
    tune_l_r <= u_sel & u_left;
    tune_r_r <= u_sel & u_right;
    if (u_sel & u_left  & ~tune_l_r & (cap_delay != 5'd0))  cap_delay <= cap_delay - 1'b1;
    if (u_sel & u_right & ~tune_r_r & (cap_delay != 5'd31)) cap_delay <= cap_delay + 1'b1;
end

// --- PmodVGA Analog Output (native core timing, zero buffering) ---
// The core's RGB lags its hcnt-derived sync/blank by a fixed pipeline delay
// (tile fetch -> gfx ROM -> palette -> output regs) - the same lag the HDMI
// capture compensates for with cap_delay. Taking hblank/hs raw here let the
// PREVIOUS line's tail leak into the first ~13 visible pixels (a garbled
// strip down the left edge) while blanking swallowed the last 13 real ones.
// Delay the sync/blank signals by the same amount so they line up with the
// pixels they describe. Shares the live-tunable cap_delay: Select + D-pad
// Right/Left adjusts both paths, value shown in the beacon as "dXX".
reg [31:0] hs_sr, vs_sr, cs_sr, hb_sr, vb_sr;
always @(posedge clk_sys) begin
    if (pixel_tick) begin
        hs_sr <= {hs_sr[30:0], hs};
        vs_sr <= {vs_sr[30:0], vs};
        cs_sr <= {cs_sr[30:0], cs};
        hb_sr <= {hb_sr[30:0], hblank};
        vb_sr <= {vb_sr[30:0], vblank};
    end
end
wire [4:0] vga_tap = (cap_delay == 5'd0) ? 5'd0 : cap_delay - 5'd1;
wire hs_d     = (cap_delay == 5'd0) ? hs     : hs_sr[vga_tap];
wire vs_d     = (cap_delay == 5'd0) ? vs     : vs_sr[vga_tap];
wire cs_d     = (cap_delay == 5'd0) ? cs     : cs_sr[vga_tap];
wire hblank_d = (cap_delay == 5'd0) ? hblank : hb_sr[vga_tap];
wire vblank_d = (cap_delay == 5'd0) ? vblank : vb_sr[vga_tap];

// 3:3:3 -> 4:4:4 by MSB replication so full intensity maps to full scale.
// Blank the DAC outside active video so the monitor sees black porches.
wire cab_blank = hblank_d | vblank_d;
assign vga_r = cab_blank ? 4'h0 : {r, r[2]};
assign vga_g = cab_blank ? 4'h0 : {g, g[2]};
assign vga_b = cab_blank ? 4'h0 : {b, b[2]};

// Sync format. 31 kHz always uses separate negative H/V (standard RGBHV).
//
// 15 kHz also defaults to SEPARATE H and V sync, for two reasons: it is what
// a real MCR cabinet expects (the Video connector has discrete H-Sync on
// pin 8 and V-Sync on pin 9), and modern 15 kHz-capable displays detect it
// reliably. Composite sync was the old default and cost a long debug session
// - one LCD silently dropped its entire green channel, apparently deciding a
// csync source must carry sync-on-green and clamping that input. Note such
// displays latch their format detection, so a wrong guess persists until
// sync is disturbed; changing format while running may not re-trigger it.
//
// Strap J10-39 to GND for composite sync on HS instead (RGBS - what an
// OSSC/RetroTink or an SOG-wired monitor may prefer).
// Strap J10-40 to GND to hold VS inactive (pure single-sync RGBS).
wire want_csync = ~map_rows_n;   // J10-39 to GND
wire vsync_off  = ~map_sock_n;   // J10-40 to GND

assign vga_hs = (tv15khz && want_csync) ? cs_d : hs_d;
assign vga_vs = vsync_off ? 1'b1 : vs_d;

// --- PmodVGA plugged directly into the PMOD sockets --------------------------
// Sipeed socket columns (anchored at the power end, which mates with the
// Pmod's VCC/GND columns): [3V3][GND][IO6/7][IO4/5][IO2/3][IO0/1].
// Digilent columns from the same end: [VCC][GND][4/10][3/9][2/8][1/7].
// => forced column pairing: Pmod pins {1,2,3,4} land on even-or-odd IOs
// {0,2,4,6} and pins {7,8,9,10} on the other row - which row is which, and
// which socket meets PmodVGA J1 (R/B) vs J2 (G/sync), depends on physical
// orientation we can't see in the schematic. Both unknowns are runtime
// straps: try the 4 combinations, exactly one shows a stable picture.
wire row_swap  = ~map_rows_n;   // strap to GND to swap rows
wire sock_swap = ~map_sock_n;   // strap to GND to swap sockets

// Socket carrying PmodVGA J1 (R + B ladders)
wire [7:0] j1_rows_a = {vga_b[3], vga_r[3], vga_b[2], vga_r[2],
                        vga_b[1], vga_r[1], vga_b[0], vga_r[0]}; // IO7..IO0
wire [7:0] j1_rows_b = {vga_r[3], vga_b[3], vga_r[2], vga_b[2],
                        vga_r[1], vga_b[1], vga_r[0], vga_b[0]};
wire [7:0] j1_bus = row_swap ? j1_rows_b : j1_rows_a;

// Socket carrying PmodVGA J2 (G ladder + HS/VS; Pmod pins 9/10 are NC)
wire [7:0] j2_rows_a = {1'b0, vga_g[3], 1'b0, vga_g[2],
                        vga_vs, vga_g[1], vga_hs, vga_g[0]};     // IO7..IO0
wire [7:0] j2_rows_b = {vga_g[3], 1'b0, vga_g[2], 1'b0,
                        vga_g[1], vga_vs, vga_g[0], vga_hs};
wire [7:0] j2_bus = row_swap ? j2_rows_b : j2_rows_a;

assign pmod0_io = sock_swap ? j2_bus : j1_bus;
assign pmod1_io = sock_swap ? j1_bus : j2_bus;

// --- HDMI Output: DDR3 framebuffer -> 1280x720@60 (nand2mario/gbatang) ------
// The core streams its native 512x480 image into a DDR3-backed framebuffer,
// which upscales to 720p (game shown 960 wide for 4:3) and drives HDMI with
// audio. This fully decouples core and display timing: no line buffer, no
// genlock, no shimmer. In 15 kHz mode the capture height drops to 240 lines
// per field and the upscaler adapts (integer 3x).

// The core's RGB output lags its hcnt by a fixed pipeline delay (tile fetch ->
// gfx ROM -> palette -> output regs); shift the capture window back by
// cap_delay so each line's pixels land at the right offsets.
// LIVE TUNING: hold Select and tap D-pad Right (+1) / Left (-1) while
// watching the left edge - garbage/overlap on the LEFT means increase.
// The current value is reported in the UART beacon as "dXX" (hex); once the
// sweet spot is found, hardcode it as the reset value below.
// (The D-pad is masked from the game while Select is held; note Select
// itself still inserts a coin - harmless during tuning.)


wire cap_active = !vblank && (core_hcnt >= {5'b0, cap_delay}) && (core_hcnt < {5'b0, cap_delay} + 10'd512);
wire fb_we = pixel_tick && cap_active;
// RGB444: replicate each 3-bit channel's MSB into bit 0 (as the VGA DAC does)
wire [11:0] fb_data = {r, r[2], g, g[2], b, b[2]};

// Single-cycle frame pulse after the last active line (vblank rising edge)
reg fb_vbl_r = 1'b1;
always @(posedge clk_sys) fb_vbl_r <= vblank;
wire fb_vsync = vblank & ~fb_vbl_r;

// DDR3/HDMI bring-up debug on spare J10 pins (probe vs GND with a DMM):
//   debug_o[0] J10-21: init_calib_complete - steady 3.3V = DDR3 trained
//   debug_o[1] J10-22: ~1.1Hz heartbeat from clk_x1 (74.25MHz pixel clock)
//   debug_o[2] J10-23: ~0.8Hz heartbeat from the 27MHz reference
//   debug_o[3] J10-24: ddr_rst - should sit LOW once the DDR PLL settles
wire fb_clk_x1, fb_ddr_rst, fb_calib;
wire fb_hclk;             // HDMI pixel clock (74.25 MHz expected)
// NOTE: do not hang a counter on hclk5 (371 MHz). It is unconstrained in the
// SDC, so the tool cannot see the speed, and the added logic disturbed the
// DDR3 interface enough to stop it calibrating (beacon showed c0). hclk5 was
// measured this way once and confirmed at 5x hclk; that is enough.
reg [24:0] hb_h = 0;
always @(posedge fb_hclk) hb_h <= hb_h + 1'b1;
reg [25:0] hb_x1 = 0;
reg [24:0] hb_27 = 0;
always @(posedge fb_clk_x1) hb_x1 <= hb_x1 + 1'b1;
always @(posedge clk27)     hb_27 <= hb_27 + 1'b1;
assign debug_o = {fb_ddr_rst, hb_27[24], hb_x1[25], fb_calib};

// Same vitals over USB-C serial (BL616 bridges the U15 UART), for debugging
// with the case closed: frozen x____ across lines = pixel clock dead,
// frozen q__ = 27MHz chain dead, c0/r1 = DDR3 never trained.
uart_beacon #(.CLK_HZ(40_000_000), .BAUD(115200)) beacon (
    .clk(clk_sys),
    .calib(fb_calib),
    .ddr_rst(fb_ddr_rst),
    .cnt_x({hb_h[24:21], hb_x1[25:14]}),
    .cnt_q(hb_27[24:17]),
    .aux({3'b000, cap_delay}),
    .aux2({hb_h[24:21], sd_ready, sd_err, ldr_done, ldr_error}),
    .txd(uart_tx)
);

ddr3_framebuffer #(
    .WIDTH(512),
    .HEIGHT(480),
    .COLOR_BITS(12),
    .PREFETCH_DELAY(44),
    .DVI_MODE(0)          // full HDMI, as NESTang uses
) fb_inst (
    .hclk_dbg(fb_hclk),
    .clk_27(clk27),
    .pll_lock_27(1'b1),
    .clk_g(clk50_pll),        // PLL-buffered 50 MHz (global clock net)
    .clk_out(fb_clk_x1),
    // Reset from the power-on counter ONLY - never from rom_ready. Video must
    // come up independently of ROM loading, otherwise a stalled/slow SD load
    // takes HDMI sync down with it and there is nothing to diagnose from.
    .rst_n(~core_reset_raw),
    .ddr_rst(fb_ddr_rst),
    .init_calib_complete(fb_calib),
    .ddr_prefetch_delay(6'd44),

    // Framebuffer write interface (core pixel stream)
    .clk(clk_sys),
    .fb_width(11'd512),
    .fb_height(tv15khz ? 10'd240 : 10'd480),
    .disp_width(11'd960),     // 4:3 within the 720p canvas
    .fb_vsync(fb_vsync),
    .fb_we(fb_we),
    .fb_data(fb_data),

    // HDMI audio (offset-binary core mix -> signed PCM)
    .sound_left(audio_l_val ^ 16'h8000),
    .sound_right(audio_r_val ^ 16'h8000),

    // DDR3 (on-SOM 4Gb x16)
    .ddr_addr(ddr_addr),
    .ddr_bank(ddr_bank),
    .ddr_cs(ddr_cs),
    .ddr_ras(ddr_ras),
    .ddr_cas(ddr_cas),
    .ddr_we(ddr_we),
    .ddr_ck(ddr_ck),
    .ddr_ck_n(ddr_ck_n),
    .ddr_cke(ddr_cke),
    .ddr_odt(ddr_odt),
    .ddr_reset_n(ddr_reset_n),
    .ddr_dm(ddr_dm),
    .ddr_dq(ddr_dq),
    .ddr_dqs(ddr_dqs),
    .ddr_dqs_n(ddr_dqs_n),

    // HDMI out
    .tmds_clk_n(tmds_clk_n),
    .tmds_clk_p(tmds_clk_p),
    .tmds_d_n(tmds_d_n),
    .tmds_d_p(tmds_d_p)
);

// --- PWM Audio Modulators ---
ds_dac dac_l (
    .clk(clk_sys),
    .resetn(~core_reset),
    .din(audio_l_val),
    .dout(audio_l)
);

ds_dac dac_r (
    .clk(clk_sys),
    .resetn(~core_reset),
    .din(audio_r_val),
    .dout(audio_r)
);

endmodule
