// game_config.vh is generated by `python3 tools/merge_roms.py <game>` and
// must match the ROM hex files: it defines GAME_TRON / GAME_DOMINO /
// GAME_SHOLLOW to select the per-game input & DIP mapping below.
`include "game_config.vh"

// Tang Console 60K Top-Level Wrapper for MCR2 Arcade Core
// Video: DDR3-backed framebuffer (nand2mario/gbatang) upscaling the core's
// native 512x480 to 1280x720 HDMI with audio, plus concurrent analog VGA
// (PmodVGA / RGB DAC) at native 31/15 kHz timing. ROMs live in BSRAM;
// gamepad on USB port 1.
module mcr2_console60k_top (
    input        sys_clk,       // 50 MHz on-board oscillator (pin V22)
    input        s1,            // User key AA13 - ACTIVE LOW on console (pull-up)
    input        reset2,        // User key AB13 - ACTIVE LOW on console (pull-up)

    // DVI/HDMI output
    output       tmds_clk_p,
    output       tmds_clk_n,
    output [2:0] tmds_d_p,
    output [2:0] tmds_d_n,

    // On-SOM DDR3 (framebuffer backing store; pins from gbatang console60k)
    output [14:0] ddr_addr,
    output [2:0]  ddr_bank,
    output        ddr_cs,
    output        ddr_ras,
    output        ddr_cas,
    output        ddr_we,
    output        ddr_ck,
    output        ddr_ck_n,
    output        ddr_cke,
    output        ddr_odt,
    output        ddr_reset_n,
    output [1:0]  ddr_dm,
    inout  [15:0] ddr_dq,
    inout  [1:0]  ddr_dqs,
    inout  [1:0]  ddr_dqs_n,

    // PMOD sockets, repurposed to host the Digilent PmodVGA directly.
    // (Desk buttons retired - inputs come from the USB pad and board keys.)
    // Sipeed socket IO order differs from Digilent pin order; the physical
    // row/socket orientation is resolved at runtime by the two map_* straps.
    output [7:0] pmod0_io,
    output [7:0] pmod1_io,
    input        map_rows_n,     // J10-39 strap: open/GND = try both
    input        map_sock_n,     // J10-40 strap: open/GND = try both

    // Digilent PmodVGA (4:4:4 + HS/VS) wired to J10 header - see CST for the
    // jumper recipe. Analog output has no line buffer -> no shimmer/tearing.
    output [3:0] vga_r,
    output [3:0] vga_g,
    output [3:0] vga_b,
    output       vga_hs,
    output       vga_vs,

    // 15/31 kHz select strap on J10 (internal pull-up):
    // open = 31 kHz progressive (VGA monitor), jumper to GND = 15 kHz
    // native arcade timing (CRT / OSSC / RetroTink; VGA LCDs will not sync)
    input        mode15_n,

    // USB-A port 1 (left) - USB HID host (15k pulldowns are on the board)
    inout        usb1_dp,
    inout        usb1_dn,

    // DDR3/HDMI bring-up debug (J10 pins 21-24; see comment at the logic)
    output [3:0] debug_o,

    // Status beacon on the FPGA->BL616 UART (shows up as USB-C serial,
    // 115200 8N1): one "FB c_ r_ x____ q__" line every ~0.5s
    output       uart_tx,

    // PWM Audio output
    output       audio_l,
    output       audio_r
);

// --- Clock Generation ---
wire clk_sys;  // 40 MHz  (Core system clock, generates 20 MHz pixel enable)
wire clk_p5;   // 125 MHz (HDMI 5x pixel clock)
wire pll_locked;

wire clk50_pll;  // PLL-buffered 50 MHz for the DDR3 controller/mDRP (clk_g).
                 // Feeding the raw pad clock there put a derived clock on
                 // generic routing (PR1014) and the DDR3 IP never came up.
gowin_pll_mcr2 pll_inst (
    .clkin(sys_clk),
    .clk_sys(clk_sys),
    .clk_p5(clk_p5),
    .clk_50(clk50_pll),
    .lock(pll_locked)
);

// 27 MHz reference for the DDR3 framebuffer's internal PLLs (720p + DDR3)
wire clk27;
pll_27 pll27_inst (
    .clkin(sys_clk),
    .clkout0(clk27)
);

// Second PLLA: 50 MHz -> exactly 12 MHz for the USB HID host
// (VCO = 50*18 = 900 MHz, ODIV0 = 75; config from nand2mario's usb_hid_host)
wire clk_usb;
gowin_pll_usb pll_usb_inst (
    .clkin(sys_clk),
    .clkout(clk_usb)
);

// --- Reset Generation ---
// Unlike the Primer 25K (buttons active high w/ pulldown), the Tang Console's
// user keys are active LOW with pull-ups. Invert once here; the rest of the
// design keys off the active-high key_s1/key_s2 exactly like the 25K top.
wire key_s1 = ~s1;
wire key_s2 = ~reset2;

// 15 kHz strap, synchronized into the core clock domain (active low pin).
// Live toggling works; if the picture is disturbed after moving the jumper,
// press S1 (reset) once.
reg mode15_s1 = 0, mode15_s2 = 0;
always @(posedge clk_sys) begin
    mode15_s1 <= ~mode15_n;
    mode15_s2 <= mode15_s1;
end
wire tv15khz = mode15_s2;

// (Video note: the DDR3 framebuffer captures whatever timing the core emits,
// so HDMI stays alive in 15 kHz mode too - capture height drops to 240
// lines per field and the upscaler adapts.)

reg [7:0] reset_cnt = 255;
wire core_reset = (reset_cnt != 0);

always @(posedge clk_sys) begin
    if (key_s1 || !pll_locked) begin
        reset_cnt <= 255;
    end else if (reset_cnt != 0) begin
        reset_cnt <= reset_cnt - 8'd1;
    end
end

// The main Z80 ROM and Sound Z80 ROM are instantiated as separate ROMs
// to ensure clean Gowin BSRAM block inference with hex initialization.
// INIT_FILE paths resolve relative to this source file's directory;
// run `python3 tools/merge_roms.py <game>` from the repo root to (re)generate.
wire [15:0] rom_addr;
wire [7:0]  rom_do;
wire [13:0] snd_addr;
wire [7:0]  snd_do;

dpram #(
    .dWidth(8),
    .aWidth(16),
    .INIT_FILE("rom_main.hex")
) rom_cpu_inst (
    .clk_a(clk_sys),
    .we_a(1'b0),
    .addr_a(rom_addr),
    .d_a(8'h00),
    .q_a(rom_do),

    .clk_b(clk_sys),
    .we_b(1'b0),
    .addr_b(16'h0000),
    .d_b(8'h00),
    .q_b() // Port B is unused
);

dpram #(
    .dWidth(8),
    .aWidth(14),
    .INIT_FILE("rom_snd.hex")
) rom_snd_inst (
    .clk_a(clk_sys),
    .we_a(1'b0),
    .addr_a(snd_addr),
    .d_a(8'h00),
    .q_a(snd_do),

    .clk_b(clk_sys),
    .we_b(1'b0),
    .addr_b(14'h0000),
    .d_b(8'h00),
    .q_b() // Port B is unused
);

// --- USB HID host (gamepad on USB-A port 1) -----------------------------------
// nand2mario usb_hid_host: low-speed USB, standard HID pads (DInput). The
// board provides the 15k host pulldowns and 5V VBUS. Runs at 12 MHz.
reg [7:0] usb_rst_cnt = 8'hFF;
wire usb_resetn = (usb_rst_cnt == 8'd0);
always @(posedge clk_usb) begin
    if (usb_rst_cnt != 0) usb_rst_cnt <= usb_rst_cnt - 8'd1;
end

wire pad_l, pad_r, pad_u, pad_d;
wire pad_a, pad_b, pad_x, pad_y, pad_sel, pad_sta;

usb_hid_host usb1 (
    .usbclk(clk_usb),
    .usbrst_n(usb_resetn),
    .usb_dm(usb1_dn),
    .usb_dp(usb1_dp),
    .typ(),
    .report(),
    .conerr(),
    .key_modifiers(), .key1(), .key2(), .key3(), .key4(),
    .mouse_btn(), .mouse_dx(), .mouse_dy(),
    .game_l(pad_l), .game_r(pad_r), .game_u(pad_u), .game_d(pad_d),
    .game_a(pad_a), .game_b(pad_b), .game_x(pad_x), .game_y(pad_y),
    .game_sel(pad_sel), .game_sta(pad_sta),
    .dbg_hid_report()
);

// Synchronize the (active-high, 12 MHz-domain) pad bits into clk_sys
reg [9:0] pad_sync1 = 0, pad_sync2 = 0;
always @(posedge clk_sys) begin
    pad_sync1 <= {pad_l, pad_r, pad_u, pad_d, pad_a, pad_b, pad_x, pad_y, pad_sel, pad_sta};
    pad_sync2 <= pad_sync1;
end
wire u_left  = pad_sync2[9], u_right = pad_sync2[8];
wire u_up    = pad_sync2[7], u_down  = pad_sync2[6];
wire u_btn_a = pad_sync2[5], u_btn_b = pad_sync2[4];
wire u_btn_x = pad_sync2[3], u_btn_y = pad_sync2[2];
wire u_sel   = pad_sync2[1], u_sta   = pad_sync2[0];

// --- Core Controls & Switch Mapping (per game, verified vs MAME mcr.cpp) -----
// All inputs come from the USB pad (PMOD sockets carry the PmodVGA):
// common decode: dpad = joystick, A = Button 1, Start = Start1,
// Select = Coin1. B/X/Y are game-specific. Board key 2 also pulses Coin 1.
wire m_left    = u_left;
wire m_right   = u_right;
wire m_up      = u_up;
wire m_down    = u_down;
wire m_start1  = u_sta;
wire m_coin1   = u_sel | key_s2;
wire m_service = 1'b0;

reg [7:0] input_0;
reg [7:0] input_1;
reg [7:0] input_2;
reg [7:0] input_3;
reg [7:0] input_4;

`ifdef GAME_TRON
// TRON: IP0 = standard MCR2 (trigger on bit 4), IP1 = 8-bit aim dial
// (absolute spinner value, NOT active-low switches), IP2 = P1 8-way
// joystick, IP3 DIPs = 0x80 (upright, coin meters 2, continues allowed,
// cocktail-trigger input idle high), IP4 = cocktail dial (unused).
// Pad: dpad = move, A/B = trigger, X/Y = rotate aim. If the aim rotates
// opposite to expectation (MAME marks this dial PORT_REVERSE), swap the
// minus/plus hookup below.
wire m_fire   = u_btn_a | u_btn_b;
wire m_start2 = 1'b0;   // X/Y are the spinner on this game
wire m_coin2  = 1'b0;

wire [7:0] spin_out;
spinner #(.INC_NORMAL(20), .INC_FAST(40), .INC_SPINNER(20)) aim_dial (
    .clk(clk_sys),
    .reset(core_reset),
    .minus(u_btn_x),
    .plus(u_btn_y),
    .fast(1'b0),
    .strobe(vblank),   // steps once per frame (module edge-detects)
    .spin_in(9'd0),    // reserved: USB mouse as a true spinner
    .spin_out(spin_out)
);

always @(*) begin
    input_0 = ~{ 1'b0, m_service, 1'b0, m_fire, m_start2, m_start1, m_coin2, m_coin1 };
    input_1 = spin_out;
    input_2 = ~{ 4'b0000, m_down, m_up, m_right, m_left };
    input_3 = 8'h80;
    input_4 = 8'h00;
end

`elsif GAME_SHOLLOW
// SATAN'S HOLLOW: IP0 = standard (no button bit), IP1 = {..., fire,
// shield, right, left}. Pad: A = fire, B = shield, X = Start2, Y = Coin2.
wire m_start2 = u_btn_x;
wire m_coin2  = u_btn_y;

always @(*) begin
    input_0 = ~{ 2'b00, 1'b0, 1'b0, m_start2, m_start1, m_coin2, m_coin1 };
    input_1 = ~{ 4'b0000, u_btn_a, u_btn_b, m_right, m_left };
    input_2 = 8'hFF;
    input_3 = 8'hFF;
    input_4 = 8'hFF;
end

`else
// DOMINO MAN (default): IP0 = standard (Place/Strike on bit 4), IP1 =
// 4-way joystick. IP3 DIPs = 0x3E: Music On, light skin, bits2-5 unused
// (idle high), Upright (bit6 LOW - 0xFF would select cocktail!), two coin
// meters. Pad: A/B = Place/Strike, X = Start2, Y = Coin2.
wire m_fire   = u_btn_a | u_btn_b;
wire m_start2 = u_btn_x;
wire m_coin2  = u_btn_y;

always @(*) begin
    input_0 = ~{ 1'b0, m_service, 1'b0, m_fire, m_start2, m_start1, m_coin2, m_coin1 };
    input_1 = ~{ 4'b0000, m_down, m_up, m_right, m_left };
    input_2 = 8'hFF;
    input_3 = 8'h3E;
    input_4 = 8'hFF;
end
`endif

// --- Core Instantiation ---
wire [2:0] r, g, b;
wire       hblank, vblank;
wire       hs, vs, cs;
wire [15:0] audio_l_val, audio_r_val;

wire [9:0] core_hcnt;
wire [9:0] core_vcnt;

mcr2 mcr2_core (
    .clock_40(clk_sys),
    .reset(core_reset),

    // Video outputs
    .video_r(r),
    .video_g(g),
    .video_b(b),
    .video_vblank(vblank),
    .video_hblank(hblank),
    .video_hs(hs),
    .video_vs(vs),
    .video_csync(cs),
    .hcnt_out(core_hcnt),
    .vcnt_out(core_vcnt),

    // 0 = 31kHz scan-doubled progressive (HDMI + VGA monitor),
    // 1 = native 15kHz arcade timing (CRT/scan converter via PmodVGA).
    // Selected by the mode15_n strap on J10.
    .tv15Khz_mode(tv15khz),

    .separate_audio(1'b0), // mono mix
    .audio_out_l(audio_l_val),
    .audio_out_r(audio_r_val),

    .input_0(input_0),
    .input_1(input_1),
    .input_2(input_2),
    .input_3(input_3),
    .input_4(input_4),

    // CPU ROM interface
    .cpu_rom_addr(rom_addr),
    .cpu_rom_do(rom_do),
    .snd_rom_addr(snd_addr),
    .snd_rom_do(snd_do),

    // Disable HPS download interface
    .dl_addr(17'd0),
    .dl_wr(1'b0),
    .dl_data(8'd0),
    .dl_nvram_wr(1'b0),
    .dl_din(),
    .dl_nvram(1'b0)
);

// --- PmodVGA Analog Output (native core timing, zero buffering) ---
// 3:3:3 -> 4:4:4 by MSB replication so full intensity maps to full scale.
// Blank the DAC outside active video so the monitor sees black porches.
wire cab_blank = hblank | vblank;
assign vga_r = cab_blank ? 4'h0 : {r, r[2]};
assign vga_g = cab_blank ? 4'h0 : {g, g[2]};
assign vga_b = cab_blank ? 4'h0 : {b, b[2]};

// 31 kHz: separate negative H/V syncs (standard VGA-style RGBHV).
// 15 kHz: composite sync on the HS pin (RGBS convention used by arcade
// monitors and OSSC/RetroTink over a VGA cable); VS still carried, harmless.
assign vga_hs = tv15khz ? cs : hs;
assign vga_vs = vs;

// --- PmodVGA plugged directly into the PMOD sockets --------------------------
// Sipeed socket columns (anchored at the power end, which mates with the
// Pmod's VCC/GND columns): [3V3][GND][IO6/7][IO4/5][IO2/3][IO0/1].
// Digilent columns from the same end: [VCC][GND][4/10][3/9][2/8][1/7].
// => forced column pairing: Pmod pins {1,2,3,4} land on even-or-odd IOs
// {0,2,4,6} and pins {7,8,9,10} on the other row - which row is which, and
// which socket meets PmodVGA J1 (R/B) vs J2 (G/sync), depends on physical
// orientation we can't see in the schematic. Both unknowns are runtime
// straps: try the 4 combinations, exactly one shows a stable picture.
wire row_swap  = ~map_rows_n;   // strap to GND to swap rows
wire sock_swap = ~map_sock_n;   // strap to GND to swap sockets

// Socket carrying PmodVGA J1 (R + B ladders)
wire [7:0] j1_rows_a = {vga_b[3], vga_r[3], vga_b[2], vga_r[2],
                        vga_b[1], vga_r[1], vga_b[0], vga_r[0]}; // IO7..IO0
wire [7:0] j1_rows_b = {vga_r[3], vga_b[3], vga_r[2], vga_b[2],
                        vga_r[1], vga_b[1], vga_r[0], vga_b[0]};
wire [7:0] j1_bus = row_swap ? j1_rows_b : j1_rows_a;

// Socket carrying PmodVGA J2 (G ladder + HS/VS; Pmod pins 9/10 are NC)
wire [7:0] j2_rows_a = {1'b0, vga_g[3], 1'b0, vga_g[2],
                        vga_vs, vga_g[1], vga_hs, vga_g[0]};     // IO7..IO0
wire [7:0] j2_rows_b = {vga_g[3], 1'b0, vga_g[2], 1'b0,
                        vga_g[1], vga_vs, vga_g[0], vga_hs};
wire [7:0] j2_bus = row_swap ? j2_rows_b : j2_rows_a;

assign pmod0_io = sock_swap ? j2_bus : j1_bus;
assign pmod1_io = sock_swap ? j1_bus : j2_bus;

// --- HDMI Output: DDR3 framebuffer -> 1280x720@60 (nand2mario/gbatang) ------
// The core streams its native 512x480 image into a DDR3-backed framebuffer,
// which upscales to 720p (game shown 960 wide for 4:3) and drives HDMI with
// audio. This fully decouples core and display timing: no line buffer, no
// genlock, no shimmer. In 15 kHz mode the capture height drops to 240 lines
// per field and the upscaler adapts (integer 3x).

// The core's RGB output lags its hcnt by a fixed pipeline delay (tile fetch ->
// gfx ROM -> palette -> output regs); shift the capture window back by
// CAP_DELAY so each line's pixels land at the right offsets. Tune by +/-1 if
// a sliver shows on the left/right edge (see handoff v3).
localparam [9:0] CAP_DELAY = 10'd13;

// One strobe per core pixel: hcnt advances at the 20 MHz pixel rate (every
// other clk_sys cycle)
reg [9:0] hcnt_r;
always @(posedge clk_sys) hcnt_r <= core_hcnt;
wire pixel_tick = (hcnt_r != core_hcnt);

wire cap_active = !vblank && (core_hcnt >= CAP_DELAY) && (core_hcnt < CAP_DELAY + 10'd512);
wire fb_we = pixel_tick && cap_active;
// RGB444: replicate each 3-bit channel's MSB into bit 0 (as the VGA DAC does)
wire [11:0] fb_data = {r, r[2], g, g[2], b, b[2]};

// Single-cycle frame pulse after the last active line (vblank rising edge)
reg fb_vbl_r = 1'b1;
always @(posedge clk_sys) fb_vbl_r <= vblank;
wire fb_vsync = vblank & ~fb_vbl_r;

// DDR3/HDMI bring-up debug on spare J10 pins (probe vs GND with a DMM):
//   debug_o[0] J10-21: init_calib_complete - steady 3.3V = DDR3 trained
//   debug_o[1] J10-22: ~1.1Hz heartbeat from clk_x1 (74.25MHz pixel clock)
//   debug_o[2] J10-23: ~0.8Hz heartbeat from the 27MHz reference
//   debug_o[3] J10-24: ddr_rst - should sit LOW once the DDR PLL settles
wire fb_clk_x1, fb_ddr_rst, fb_calib;
reg [25:0] hb_x1 = 0;
reg [24:0] hb_27 = 0;
always @(posedge fb_clk_x1) hb_x1 <= hb_x1 + 1'b1;
always @(posedge clk27)     hb_27 <= hb_27 + 1'b1;
assign debug_o = {fb_ddr_rst, hb_27[24], hb_x1[25], fb_calib};

// Same vitals over USB-C serial (BL616 bridges the U15 UART), for debugging
// with the case closed: frozen x____ across lines = pixel clock dead,
// frozen q__ = 27MHz chain dead, c0/r1 = DDR3 never trained.
uart_beacon #(.CLK_HZ(40_000_000), .BAUD(115200)) beacon (
    .clk(clk_sys),
    .calib(fb_calib),
    .ddr_rst(fb_ddr_rst),
    .cnt_x(hb_x1[25:10]),
    .cnt_q(hb_27[24:17]),
    .txd(uart_tx)
);

ddr3_framebuffer #(
    .WIDTH(512),
    .HEIGHT(480),
    .COLOR_BITS(12),
    .PREFETCH_DELAY(44)
) fb_inst (
    .clk_27(clk27),
    .pll_lock_27(1'b1),
    .clk_g(clk50_pll),        // PLL-buffered 50 MHz (global clock net)
    .clk_out(fb_clk_x1),
    .rst_n(~core_reset),
    .ddr_rst(fb_ddr_rst),
    .init_calib_complete(fb_calib),
    .ddr_prefetch_delay(6'd44),

    // Framebuffer write interface (core pixel stream)
    .clk(clk_sys),
    .fb_width(11'd512),
    .fb_height(tv15khz ? 10'd240 : 10'd480),
    .disp_width(11'd960),     // 4:3 within the 720p canvas
    .fb_vsync(fb_vsync),
    .fb_we(fb_we),
    .fb_data(fb_data),

    // HDMI audio (offset-binary core mix -> signed PCM)
    .sound_left(audio_l_val ^ 16'h8000),
    .sound_right(audio_r_val ^ 16'h8000),

    // DDR3 (on-SOM 4Gb x16)
    .ddr_addr(ddr_addr),
    .ddr_bank(ddr_bank),
    .ddr_cs(ddr_cs),
    .ddr_ras(ddr_ras),
    .ddr_cas(ddr_cas),
    .ddr_we(ddr_we),
    .ddr_ck(ddr_ck),
    .ddr_ck_n(ddr_ck_n),
    .ddr_cke(ddr_cke),
    .ddr_odt(ddr_odt),
    .ddr_reset_n(ddr_reset_n),
    .ddr_dm(ddr_dm),
    .ddr_dq(ddr_dq),
    .ddr_dqs(ddr_dqs),
    .ddr_dqs_n(ddr_dqs_n),

    // HDMI out
    .tmds_clk_n(tmds_clk_n),
    .tmds_clk_p(tmds_clk_p),
    .tmds_d_n(tmds_d_n),
    .tmds_d_p(tmds_d_p)
);

// --- PWM Audio Modulators ---
ds_dac dac_l (
    .clk(clk_sys),
    .resetn(~core_reset),
    .din(audio_l_val),
    .dout(audio_l)
);

ds_dac dac_r (
    .clk(clk_sys),
    .resetn(~core_reset),
    .din(audio_r_val),
    .dout(audio_r)
);

endmodule
